import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { Fish24RolePreviewService } from '../../../../core/fish24/dev/fish24-role-preview.service';
import { EmployerTicketRecord, Fish24TicketDepartment, Fish24TicketPreviewService, Fish24TicketStatus, FISH24_TICKET_DEPARTMENTS } from '../../../../core/fish24/tickets/fish24-ticket-preview.service';
import { InternalListColumn, InternalListColumnSearches, InternalListSort, filterByInternalListColumns, nextInternalListSort, sortInternalListRows } from '../../../../shared/ui/data-list/internal-list.model';
import { InternalListPreferencesService } from '../../../../shared/ui/data-list/internal-list-preferences.service';
import { PlainXlsxService } from '../../../../shared/ui/data-list/plain-xlsx.service';
import { IconComponent } from '../../../../shared/ui/icon/icon.component';
import { ToastService } from '../../../../shared/ui/toast/toast.service';

export interface InternalTicketFilters { readonly status: 'all' | Fish24TicketStatus; readonly title: string; readonly department: 'all' | Fish24TicketDepartment; }
export const INTERNAL_TICKET_LIST_ID='internal-tickets'; export const INTERNAL_TICKET_DEFAULTS:InternalTicketFilters={status:'all',title:'',department:'all'};
export function validateInternalTicketFilters(value:unknown):InternalTicketFilters|null{if(typeof value!=='object'||value===null)return null;const v=value as Partial<InternalTicketFilters>;return{status:v.status==='نیاز به بررسی'||v.status==='جواب داده شده'||v.status==='بسته شده'?v.status:'all',title:typeof v.title==='string'?v.title.slice(0,200):'',department:v.department==='management'||v.department==='sales'||v.department==='support'?v.department:'all'};}
export function filterInternalTickets(rows:readonly EmployerTicketRecord[],f:InternalTicketFilters):readonly EmployerTicketRecord[]{const q=f.title.trim().toLocaleLowerCase('fa-IR');return rows.filter(r=>(f.status==='all'||r.status===f.status)&&(!q||r.subject.toLocaleLowerCase('fa-IR').includes(q))&&(f.department==='all'||r.recipientDepartment===f.department));}

@Component({selector:'app-internal-tickets',standalone:true,imports:[FormsModule,RouterLink,IconComponent],template:`<div class="mx-auto max-w-[95%] space-y-4" dir="rtl"><header class="flex items-center gap-3"><div class="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10"><ui-icon name="ticket" [size]="26" class="text-primary"></ui-icon></div><div><h1 class="text-2xl font-bold text-primary sm:text-3xl">مدیریت تیکت‌ها</h1><p class="text-sm text-muted">تاریخچه مشترک تیکت‌های کارفرمایان</p></div></header>
<section class="card p-4"><h2 class="mb-3 text-lg font-extrabold">جستجو</h2><form class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3" (submit)="apply($event)"><div><label class="label">وضعیت</label><select [(ngModel)]="draft.status" name="status" class="input"><option value="all">همه وضعیت‌ها</option><option value="نیاز به بررسی">نیاز به بررسی</option><option value="جواب داده شده">جواب داده شده</option><option value="بسته شده">بسته شده</option></select></div><div><label class="label">عنوان تیکت</label><input [(ngModel)]="draft.title" name="title" class="input"></div><div><label class="label">دریافت‌کننده</label><select [(ngModel)]="draft.department" name="department" class="input"><option value="all">همه بخش‌ها</option>@for(d of departments;track d.id){<option [value]="d.id">{{d.label}}</option>}</select></div><div class="flex gap-2 xl:col-span-3 xl:justify-end"><button class="primary" type="submit">جستجو</button><button class="secondary" type="button" (click)="showAll()">مشاهده همه</button></div></form></section>
<section class="card overflow-hidden"><div class="flex flex-col gap-3 border-b border-border p-4 sm:flex-row sm:items-center sm:justify-between"><h2 class="text-lg font-extrabold">لیست تیکت‌ها ({{number(filtered().length)}} رکورد)</h2><div class="flex gap-2"><button type="button" class="toolbar" (click)="chooser.set(!chooser())">انتخاب ستون</button>@if(canExport()){<button type="button" class="toolbar text-success" (click)="exportRows()">Excel</button>}</div></div>@if(chooser()){<div class="flex flex-wrap gap-2 border-b border-border p-3">@for(c of columns;track c.id){<label class="choice"><input type="checkbox" [checked]="visible(c.id)" [disabled]="only(c.id)" (change)="toggle(c.id,$event)">{{c.label}}</label>}<button type="button" class="text-xs font-bold text-primary" (click)="restore()">ستون‌های پیش‌فرض</button></div>}
<div class="max-h-[58vh] max-w-full overflow-auto"><table class="w-full min-w-max text-sm"><thead class="sticky top-0 z-20 bg-background/95 dark:bg-slate-900/95"><tr>@for(c of visibleColumns();track c.id){<th class="px-2 py-3 text-right" [style.min-width]="c.minWidth"><button type="button" class="flex w-full justify-between" (click)="sort(c.id)"><span>{{c.label}}</span><span>{{mark(c.id)}}</span></button></th>}<th class="sticky left-0 min-w-24 bg-background/95 px-2">عملیات</th></tr><tr>@for(c of visibleColumns();track c.id){<th class="px-2 pb-2"><input type="search" class="header-search" [value]="searches()[c.id]||''" (input)="search(c.id,value($event))" [attr.aria-label]="'جستجو در '+c.label"></th>}<th class="sticky left-0 bg-background/95"></th></tr></thead><tbody class="divide-y divide-border">@for(row of pageRows();track row.id){<tr>@for(c of visibleColumns();track c.id){<td class="px-2 py-3" [attr.dir]="c.ltr?'ltr':null">@if(c.id==='status'){<span [class]="statusClass(row.status)">{{row.status}}</span>}@else{ {{cell(c,row)}} }</td>}<td class="sticky left-0 bg-surface px-2 text-center"><a [routerLink]="['/fish24/internal/tickets',row.id]" class="op" title="مشاهده"><ui-icon name="eye" [size]="16"></ui-icon></a></td></tr>}@if(!pageRows().length){<tr><td [attr.colspan]="visibleColumns().length+1" class="p-10 text-center">رکوردی پیدا نشد.</td></tr>}</tbody></table></div><div class="flex items-center justify-between border-t border-border p-3"><span>صفحه {{page()}} از {{pageCount()}}</span><div class="flex gap-2"><button class="secondary" [disabled]="page()<=1" (click)="page.set(page()-1)">قبلی</button><button class="secondary" [disabled]="page()>=pageCount()" (click)="page.set(page()+1)">بعدی</button></div></div></section></div>`,styles:[`.card{border:1px solid rgb(var(--color-border));border-radius:1rem;background:rgb(var(--color-surface));box-shadow:0 1px 3px rgb(15 23 42/.08)}.label{display:block;margin-bottom:.35rem;font-size:.8rem;font-weight:700}.input{width:100%;min-height:2.75rem;border:1px solid rgb(var(--color-border));border-radius:.75rem;background:rgb(var(--color-background));padding-inline:.75rem}.primary,.secondary,.toolbar{display:inline-flex;min-height:2.5rem;align-items:center;justify-content:center;border-radius:.75rem;padding-inline:.85rem;font-size:.8rem;font-weight:700}.primary{background:rgb(var(--color-primary));color:white}.secondary,.toolbar{border:1px solid rgb(var(--color-border))}.header-search{height:2.25rem;width:100%;border:1px solid rgb(var(--color-border));border-radius:.5rem;background:rgb(var(--color-surface));padding-inline:.5rem}.choice{display:flex;align-items:center;gap:.4rem;border:1px solid rgb(var(--color-border));border-radius:.5rem;padding:.4rem .6rem;font-size:.75rem}.op{display:inline-flex;height:2rem;width:2rem;align-items:center;justify-content:center;border:1px solid rgb(var(--color-primary)/.4);border-radius:.5rem;color:rgb(var(--color-primary))}`]})
export class InternalTicketsComponent{
 private readonly service=inject(Fish24TicketPreviewService);private readonly roles=inject(Fish24RolePreviewService);private readonly prefs=inject(InternalListPreferencesService);private readonly xlsx=inject(PlainXlsxService);private readonly toast=inject(ToastService);readonly departments=FISH24_TICKET_DEPARTMENTS;
 readonly columns:readonly InternalListColumn<EmployerTicketRecord>[]=[{id:'id',label:'شناسه',value:r=>String(r.id),exportValue:r=>String(r.id),minWidth:'7rem',ltr:true},{id:'recipient',label:'دریافت‌کننده',value:r=>this.service.departmentLabel(r.recipientDepartment),minWidth:'9rem'},{id:'subject',label:'عنوان تیکت',value:r=>r.subject,minWidth:'18rem'},{id:'mobile',label:'موبایل ارسال‌کننده',value:r=>r.employerMobile,exportValue:r=>r.employerMobile,minWidth:'10rem',ltr:true},{id:'name',label:'نام ارسال‌کننده',value:r=>r.employerName,minWidth:'11rem'},{id:'company',label:'شرکت ارسال‌کننده',value:r=>r.companyName,minWidth:'14rem'},{id:'status',label:'وضعیت',value:r=>r.status,minWidth:'10rem'},{id:'updated',label:'بروزرسانی',value:r=>r.updatedAt,exportValue:r=>r.updatedAt,minWidth:'11rem',ltr:true}];readonly defaults=this.columns.map(c=>c.id);private restored=this.prefs.loadFilters(INTERNAL_TICKET_LIST_ID,INTERNAL_TICKET_DEFAULTS,validateInternalTicketFilters);draft={...this.restored};readonly applied=signal(this.restored);readonly selected=signal<readonly string[]>(this.prefs.load(INTERNAL_TICKET_LIST_ID,this.defaults,this.defaults));readonly visibleColumns=computed(()=>this.columns.filter(c=>this.selected().includes(c.id)));readonly searches=signal<InternalListColumnSearches>({});readonly order=signal<InternalListSort>({columnId:null,direction:null});readonly chooser=signal(false);readonly page=signal(1);readonly pageSize=10;readonly all=computed(()=>this.service.internalTickets(this.roles.getPreviewRole()));readonly filtered=computed(()=>filterInternalTickets(this.all(),this.applied()));readonly table=computed(()=>sortInternalListRows(filterByInternalListColumns(this.filtered(),this.columns,this.selected(),this.searches()),this.columns,this.order()));readonly pageCount=computed(()=>Math.max(1,Math.ceil(this.table().length/this.pageSize)));readonly pageRows=computed(()=>this.table().slice((Math.min(this.page(),this.pageCount())-1)*this.pageSize,Math.min(this.page(),this.pageCount())*this.pageSize));readonly canExport=computed(()=>this.service.canExport(this.roles.getPreviewRole()));
 apply(e:Event){e.preventDefault();const f=validateInternalTicketFilters(this.draft)!;this.draft={...f};this.applied.set(f);this.prefs.saveFilters(INTERNAL_TICKET_LIST_ID,f);this.page.set(1);}showAll(){this.draft={...INTERNAL_TICKET_DEFAULTS};this.applied.set(INTERNAL_TICKET_DEFAULTS);this.prefs.resetFilters(INTERNAL_TICKET_LIST_ID);this.page.set(1);}visible(id:string){return this.selected().includes(id);}only(id:string){return this.visible(id)&&this.selected().length===1;}toggle(id:string,e:Event){const checked=(e.target as HTMLInputElement).checked;const next=checked?[...this.selected(),id]:this.selected().filter(v=>v!==id);if(next.length)this.selected.set(this.prefs.save(INTERNAL_TICKET_LIST_ID,next,this.defaults));}restore(){this.selected.set(this.prefs.reset(INTERNAL_TICKET_LIST_ID,this.defaults,this.defaults));this.searches.set({});this.order.set({columnId:null,direction:null});}search(id:string,q:string){this.searches.update(v=>({...v,[id]:q}));this.page.set(1);}sort(id:string){this.order.update(v=>nextInternalListSort(v,id));this.page.set(1);}mark(id:string){const s=this.order();return s.columnId!==id?'↕':s.direction==='asc'?'↑':'↓';}value(e:Event){return(e.target as HTMLInputElement).value;}cell(c:InternalListColumn<EmployerTicketRecord>,r:EmployerTicketRecord){return String(c.value(r)??'');}number(v:number){return new Intl.NumberFormat('fa-IR').format(v);}statusClass(s:string){return`inline-flex rounded-full px-2 py-1 text-xs font-bold ${s==='نیاز به بررسی'?'bg-warning/15 text-warning':s==='جواب داده شده'?'bg-success/15 text-success':'bg-muted/15 text-muted'}`;}
 exportRows(){const role=this.roles.getPreviewRole();if(!this.service.canExport(role)){this.toast.show('نقش پشتیبانی مجوز خروجی Excel ندارد.','error');return;}const cols=this.visibleColumns();const rows=this.filtered().map(r=>cols.map(c=>c.exportValue?c.exportValue(r):c.value(r)==null?null:String(c.value(r))));this.xlsx.export('fish24-internal-tickets.xlsx',cols.map(c=>c.label),rows);this.toast.show(`${this.number(rows.length)} تیکت برای Excel آماده شد.`,'success');}
}
