import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../../core/auth/auth.service';
import { Fish24RolePreviewService } from '../../../../core/fish24/dev/fish24-role-preview.service';
import { EmployerTicketMessage, Fish24TicketAttachment, Fish24TicketDepartment, Fish24TicketPreviewService, FISH24_TICKET_DEPARTMENTS } from '../../../../core/fish24/tickets/fish24-ticket-preview.service';
import { IconComponent } from '../../../../shared/ui/icon/icon.component';
import { ToastService } from '../../../../shared/ui/toast/toast.service';

@Component({selector:'app-internal-ticket-view',standalone:true,imports:[FormsModule,RouterLink,IconComponent],template:`@if(ticket();as t){<div class="mx-auto max-w-7xl space-y-4" dir="rtl"><header class="card flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><h1 class="text-xl font-extrabold sm:text-2xl">{{t.subject}}</h1><span [class]="statusClass(t.status)">{{t.status}}</span></div><p class="mt-1 text-sm text-muted">تیکت #{{t.id}} · ایجاد {{t.createdAt}} · بروزرسانی {{t.updatedAt}}</p></div><div class="flex flex-wrap gap-2"><a routerLink="/fish24/internal/tickets" class="secondary">بازگشت به فهرست</a><button type="button" (click)="toggleClosed()" [class]="t.status==='بسته شده'?'primary':'danger'">{{t.status==='بسته شده'?'بازگشایی تیکت':'بستن تیکت'}}</button></div></header>
<div class="grid gap-4 lg:grid-cols-[minmax(0,1fr)_20rem]"><main class="space-y-4"><section class="card p-4 sm:p-5"><h2 class="mb-4 text-lg font-extrabold">گفت‌وگو</h2><ol class="space-y-3">@for(m of t.messages;track m.id){<li [class]="m.senderSide==='internal'?'flex justify-end':'flex justify-start'"><article [class]="m.senderSide==='internal'?'message internal':'message employer'"><div class="flex flex-wrap justify-between gap-2"><div><strong>{{m.authorName}}</strong><span class="mr-2 text-xs text-muted">{{m.authorRole}}</span></div><time class="text-xs text-muted" dir="ltr">{{m.sentAt}}</time></div><p class="mt-3 whitespace-pre-wrap break-words leading-7">{{m.text}}</p>@if(m.attachments.length){<div class="mt-3 grid gap-2 sm:grid-cols-2">@for(f of m.attachments;track f.id){<button type="button" (click)="download(m,f)" class="attachment"><ui-icon name="paperclip" [size]="17"></ui-icon><span class="min-w-0 flex-1 truncate text-right">{{f.name}}</span><small>{{size(f.size)}}</small></button>}</div>}</article></li>}</ol></section>
@if(t.status!=='بسته شده'){<section class="card p-4"><h2 class="text-lg font-extrabold">پاسخ به کارفرما</h2><form class="mt-3 space-y-3" (submit)="submit($event)"><textarea [(ngModel)]="text" name="text" rows="5" class="input h-auto py-3" placeholder="متن پاسخ را بنویسید..."></textarea><input type="file" multiple accept=".jpg,.jpeg,.png,.gif,.webp,.pdf,.doc,.docx,.xls,.xlsx,.zip" (change)="selectFiles($event)" class="input">@if(error()){<p class="text-sm font-bold text-danger">{{error()}}</p>}<div class="flex flex-wrap gap-2">@for(f of files();track f.name+f.size){<span class="chip">{{f.name}} <button type="button" (click)="remove($index)">×</button></span>}</div><button class="primary" type="submit" [disabled]="submitting()">ارسال پاسخ</button></form></section>}@else{<section class="card p-5 text-center"><p class="font-bold">تیکت بسته است؛ ثبت پاسخ و ارجاع غیرفعال است.</p><button class="primary mt-3" type="button" (click)="toggleClosed()">بازگشایی تیکت</button></section>}</main>
<aside class="space-y-4"><section class="card p-4"><h2 class="text-lg font-extrabold">اطلاعات تیکت</h2><dl class="mt-3 space-y-3 text-sm"><div><dt>کارفرما</dt><dd>{{t.employerName}}</dd></div><div><dt>شرکت / کارگاه</dt><dd>{{t.companyName||'—'}}</dd></div><div><dt>موبایل</dt><dd dir="ltr">{{t.employerMobile}}</dd></div><div><dt>دریافت‌کننده</dt><dd>{{service.departmentLabel(t.recipientDepartment)}}</dd></div></dl></section>
<section class="card p-4"><h2 class="text-lg font-extrabold">ارجاع تیکت</h2><select [(ngModel)]="referral" class="input mt-3" [disabled]="t.status==='بسته شده'">@for(d of departments;track d.id){<option [value]="d.id">{{d.label}}</option>}</select><button type="button" class="secondary mt-2 w-full" [disabled]="t.status==='بسته شده'" (click)="refer()">ارجاع</button></section>
<section class="card p-4"><h2 class="text-lg font-extrabold">سابقه ارجاع <span class="text-xs text-muted">فقط پنل داخلی</span></h2>@if(t.referrals.length){<ol class="mt-3 space-y-3">@for(r of t.referrals;track r.id){<li class="rounded-xl bg-background p-3 text-sm"><strong>{{service.departmentLabel(r.from)}} ← {{service.departmentLabel(r.to)}}</strong><p class="mt-1 text-xs text-muted">{{r.referredBy}} · {{r.referredAt}}</p></li>}</ol>}@else{<p class="mt-3 text-sm text-muted">ارجاعی ثبت نشده است.</p>}</section></aside></div></div>}`,styles:[`.card{border:1px solid rgb(var(--color-border));border-radius:1rem;background:rgb(var(--color-surface));box-shadow:0 1px 3px rgb(15 23 42/.08)}.input{width:100%;min-height:2.75rem;border:1px solid rgb(var(--color-border));border-radius:.75rem;background:rgb(var(--color-background));padding-inline:.75rem}.primary,.secondary,.danger{display:inline-flex;min-height:2.6rem;align-items:center;justify-content:center;border-radius:.75rem;padding-inline:1rem;font-size:.85rem;font-weight:700}.primary{background:rgb(var(--color-primary));color:#fff}.danger{background:rgb(var(--color-danger));color:#fff}.secondary{border:1px solid rgb(var(--color-border))}.message{width:100%;max-width:46rem;border:1px solid rgb(var(--color-border));border-radius:1rem;padding:1rem}.employer{background:rgb(var(--color-background)/.7)}.internal{background:rgb(var(--color-primary)/.08);border-color:rgb(var(--color-primary)/.2)}.attachment{display:flex;align-items:center;gap:.5rem;border:1px solid rgb(var(--color-border));border-radius:.75rem;padding:.6rem}.chip{border:1px solid rgb(var(--color-border));border-radius:.5rem;padding:.35rem .6rem;font-size:.75rem}.chip button{color:rgb(var(--color-danger))}dt{color:rgb(var(--color-muted));font-size:.75rem}dd{margin-top:.2rem;font-weight:700}`]})
export class InternalTicketViewComponent{
 readonly service=inject(Fish24TicketPreviewService);private readonly roles=inject(Fish24RolePreviewService);private readonly auth=inject(AuthService);private readonly router=inject(Router);private readonly toast=inject(ToastService);private readonly id=Number(inject(ActivatedRoute).snapshot.paramMap.get('id'));readonly departments=FISH24_TICKET_DEPARTMENTS;readonly ticket=computed(()=>this.service.findInternalTicket(this.id,this.roles.getPreviewRole()));readonly files=signal<readonly File[]>([]);readonly error=signal('');readonly submitting=signal(false);text='';referral:Fish24TicketDepartment='support';private key=this.newKey();
 constructor(){const t=this.ticket();if(!t)queueMicrotask(()=>void this.router.navigate(['/fish24/internal/tickets']));else this.referral=t.recipientDepartment;}
 submit(e:Event){e.preventDefault();if(this.submitting())return;const err=this.service.validateAttachments(this.files());if(!this.text.trim()||err){this.error.set(err??'متن پاسخ الزامی است.');return;}this.submitting.set(true);const r=this.service.internalReply(this.id,this.roles.getPreviewRole(),this.auth.currentUser()?.fullName??'کاربر داخلی',this.text,this.files(),this.key);this.submitting.set(false);if(!r.ok){this.error.set(r.error==='closed'?'تیکت بسته است.':'پاسخ ثبت نشد.');return;}this.text='';this.files.set([]);this.error.set('');this.key=this.newKey();this.toast.show('پاسخ داخلی ثبت شد.','success');}
 toggleClosed(){const t=this.ticket();if(!t)return;const r=t.status==='بسته شده'?this.service.reopenInternal(t.id,this.roles.getPreviewRole()):this.service.closeInternal(t.id,this.roles.getPreviewRole());if(r.ok)this.toast.show(t.status==='بسته شده'?'تیکت بازگشایی شد.':'تیکت بسته شد.','success');}
 refer(){const r=this.service.refer(this.id,this.roles.getPreviewRole(),this.referral,this.auth.currentUser()?.fullName??'کاربر داخلی');this.toast.show(r.ok?'تیکت ارجاع شد.':r.error==='closed'?'ابتدا تیکت را بازگشایی کنید.':'دپارتمان مقصد تغییری نکرده است.',r.ok?'success':'error');}
 selectFiles(e:Event){const i=e.target as HTMLInputElement;const next=[...this.files(),...Array.from(i.files??[])];const err=this.service.validateAttachments(next);this.error.set(err??'');if(!err)this.files.set(next);i.value='';}remove(index:number){this.files.set(this.files().filter((_,i)=>i!==index));this.error.set('');}download(m:EmployerTicketMessage,f:Fish24TicketAttachment){const blob=this.service.attachmentBlob(this.id,m.id,f.id,{role:this.roles.getPreviewRole()});if(!blob)return;const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),0);}size(v:number){return v<1048576?`${Math.ceil(v/1024)} کیلوبایت`:`${(v/1048576).toFixed(1)} مگابایت`;}statusClass(s:string){return`inline-flex rounded-full px-3 py-1 text-xs font-bold ${s==='نیاز به بررسی'?'bg-warning/15 text-warning':s==='جواب داده شده'?'bg-success/15 text-success':'bg-muted/15 text-muted'}`;}private newKey(){return`internal-reply-${Date.now()}-${Math.random()}`;}
}
