import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { Fish24DocumentDistributionPreviewService, Fish24DocumentSend } from '../../../../core/fish24/financial/fish24-document-distribution-preview.service';
import { normalizeFish24Digits, normalizeJalaliDate } from '../../../../core/fish24/financial/fish24-financial-preview.service';
import { Fish24TransactionPreviewService } from '../../../../core/fish24/financial/fish24-transaction-preview.service';
import { Fish24TransactionDirection, Fish24WalletPreviewService, Fish24WalletTransaction, parsePositiveRialAmount } from '../../../../core/fish24/financial/fish24-wallet-preview.service';
import { EscToCloseDirective } from '../../../../shared/directives/esc-to-close.directive';
import { IconComponent } from '../../../../shared/ui/icon/icon.component';
import { InternalListColumn, InternalListColumnSearches, InternalListSort, filterByInternalListColumns, nextInternalListSort, sortInternalListRows } from '../../../../shared/ui/data-list/internal-list.model';
import { InternalListPreferencesService } from '../../../../shared/ui/data-list/internal-list-preferences.service';
import { PlainXlsxService } from '../../../../shared/ui/data-list/plain-xlsx.service';
import { ToastService } from '../../../../shared/ui/toast/toast.service';
import { BusinessUserPreviewService, BusinessUserRecord } from '../users/business-user-preview.service';

type StatusFilter = 'all' | 'success' | 'failed';
type DirectionFilter = 'all' | Fish24TransactionDirection;
type InvoiceFilter = 'all' | 'with' | 'without';
interface TransactionFilters { readonly name: string; readonly mobile: string; readonly company: string; readonly amount: string; readonly trackingCode: string; readonly status: StatusFilter; readonly fromTimestamp: string; readonly toTimestamp: string; readonly direction: DirectionFilter; readonly exactDebit: string; readonly exactCredit: string; readonly invoice: InvoiceFilter; }
interface ManualDraft { employerId: string; amountRial: string; direction: Fish24TransactionDirection; }
type ConfirmKind = 'manual' | 'issue-invoice' | 'delete-invoice';
interface PendingAction { readonly kind: ConfirmKind; readonly transactionId?: string; }

const LIST_ID = 'internal-transactions';
const FILTER_DEFAULTS: TransactionFilters = { name: '', mobile: '', company: '', amount: '', trackingCode: '', status: 'all', fromTimestamp: '', toTimestamp: '', direction: 'all', exactDebit: '', exactCredit: '', invoice: 'all' };
const COLUMNS: readonly InternalListColumn<Fish24WalletTransaction>[] = [
  { id: 'id', label: 'شناسه', value: row => row.id, minWidth: '7rem', ltr: true },
  { id: 'invoice', label: 'شماره فاکتور رسمی', value: row => row.formalInvoiceNumber ?? '', minWidth: '10rem', ltr: true },
  { id: 'mobile', label: 'موبایل', value: row => row.mobile, minWidth: '10rem', ltr: true },
  { id: 'name', label: 'نام', value: row => row.fullName, minWidth: '11rem' },
  { id: 'company', label: 'شرکت', value: row => row.companyName, minWidth: '13rem' },
  { id: 'createdAt', label: 'تاریخ و ساعت', value: row => row.createdAt, minWidth: '11rem', ltr: true },
  { id: 'description', label: 'توضیحات', value: row => row.description, minWidth: '15rem' },
  { id: 'workplace', label: 'شرکت / کارگاه', value: row => row.workplaceName, minWidth: '13rem' },
  { id: 'tracking', label: 'کد پیگیری', value: row => row.trackingCode, minWidth: '11rem', ltr: true },
  { id: 'userType', label: 'نوع کاربر', value: row => row.userType, minWidth: '8rem' },
  { id: 'status', label: 'وضعیت', value: row => row.status === 'success' ? 'موفق' : 'ناموفق', minWidth: '8rem' },
  { id: 'debit', label: 'بدهکار', value: row => row.direction === 'debit' ? row.amountRial : null, exportValue: row => row.direction === 'debit' ? row.amountRial : null, minWidth: '10rem' },
  { id: 'credit', label: 'بستانکار', value: row => row.direction === 'credit' ? row.amountRial : null, exportValue: row => row.direction === 'credit' ? row.amountRial : null, minWidth: '10rem' }
];

function storedAmount(value: unknown): string { return typeof value === 'string' && (!value || parsePositiveRialAmount(value) !== null) ? normalizeFish24Digits(value).trim() : ''; }
function storedTimestamp(value: unknown, endOfDay = false): string {
  if (typeof value !== 'string' || !value) return '';
  const normalized = normalizeFish24Digits(value).trim();
  const match = /^(\d{4}\/\d{1,2}\/\d{1,2})(?:\s+(\d{1,2}):(\d{2}))?$/.exec(normalized);
  const date = match ? normalizeJalaliDate(match[1]) : null;
  if (!date || (match?.[2] && (Number(match[2]) > 23 || Number(match[3]) > 59))) return '';
  return match?.[2] ? `${date} ${match[2].padStart(2, '0')}:${match[3]}` : `${date} ${endOfDay ? '23:59' : '00:00'}`;
}
function validateStoredFilters(value: unknown): TransactionFilters | null {
  if (typeof value !== 'object' || value === null) return null;
  const item = value as Partial<TransactionFilters>;
  const text = (candidate: unknown) => typeof candidate === 'string' ? candidate.trim() : '';
  const status: StatusFilter = item.status === 'success' || item.status === 'failed' ? item.status : 'all';
  const direction: DirectionFilter = item.direction === 'debit' || item.direction === 'credit' ? item.direction : 'all';
  const invoice: InvoiceFilter = item.invoice === 'with' || item.invoice === 'without' ? item.invoice : 'all';
  return { name: text(item.name), mobile: normalizeFish24Digits(text(item.mobile)).replace(/\D/g, '').slice(0, 11), company: text(item.company), amount: storedAmount(item.amount), trackingCode: text(item.trackingCode), status, fromTimestamp: storedTimestamp(item.fromTimestamp), toTimestamp: storedTimestamp(item.toTimestamp, true), direction, exactDebit: storedAmount(item.exactDebit), exactCredit: storedAmount(item.exactCredit), invoice };
}

@Component({
  selector: 'app-internal-transactions', standalone: true, imports: [FormsModule, EscToCloseDirective, IconComponent],
  template: `
  <div class="mx-auto max-w-[95%] space-y-4 animate-fade-in-up sm:space-y-5" dir="rtl">
    <header class="flex min-w-0 items-center gap-3"><div class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary/10"><ui-icon name="credit-card" [size]="25" class="text-primary"></ui-icon></div><div><h1 class="text-2xl font-bold text-primary sm:text-3xl">لیست تراکنش‌ها</h1><p class="text-sm text-muted">گزارش یکپارچه گردش مالی و تراکنش‌های دستی</p></div></header>

    <section class="card p-3 sm:p-5" aria-labelledby="transaction-filter-title">
      <div class="mb-3 flex flex-wrap items-center justify-between gap-3"><div class="flex items-center gap-2"><ui-icon name="search" [size]="19" class="text-primary"></ui-icon><h2 id="transaction-filter-title" class="text-lg font-extrabold">جستجو</h2></div><button type="button" (click)="openManual()" class="primary"><ui-icon name="plus" [size]="17"></ui-icon>تراکنش دستی</button></div>
      <form class="grid grid-cols-1 items-end gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6" (submit)="applyFilters($event)">
        <div><label class="label">نام</label><input [(ngModel)]="draft.name" name="name" class="input"></div>
        <div><label class="label">موبایل</label><input [(ngModel)]="draft.mobile" name="mobile" inputmode="numeric" dir="ltr" class="input text-left"></div>
        <div><label class="label">شرکت</label><input [(ngModel)]="draft.company" name="company" class="input"></div>
        <div><label class="label">مبلغ دقیق</label><input [(ngModel)]="draft.amount" name="amount" inputmode="numeric" class="input"></div>
        <div><label class="label">کد پیگیری</label><input [(ngModel)]="draft.trackingCode" name="tracking" dir="ltr" class="input text-left"></div>
        <div><label class="label">وضعیت</label><select [(ngModel)]="draft.status" name="status" class="input"><option value="all">همه</option><option value="success">موفق</option><option value="failed">ناموفق</option></select></div>
        <div><label class="label">از تاریخ و ساعت</label><input [(ngModel)]="draft.fromTimestamp" name="from" dir="ltr" placeholder="1405/06/01 08:00" class="input text-left"></div>
        <div><label class="label">تا تاریخ و ساعت</label><input [(ngModel)]="draft.toTimestamp" name="to" dir="ltr" placeholder="1405/06/30 23:59" class="input text-left"></div>
        <div><label class="label">نوع تراکنش</label><select [(ngModel)]="draft.direction" name="direction" class="input"><option value="all">بدهکار و بستانکار</option><option value="debit">بدهکار</option><option value="credit">بستانکار</option></select></div>
        <div><label class="label">مبلغ دقیق بدهکار</label><input [(ngModel)]="draft.exactDebit" name="debit" inputmode="numeric" class="input"></div>
        <div><label class="label">مبلغ دقیق بستانکار</label><input [(ngModel)]="draft.exactCredit" name="credit" inputmode="numeric" class="input"></div>
        <div><label class="label">فاکتور رسمی</label><select [(ngModel)]="draft.invoice" name="invoice" class="input"><option value="all">همه</option><option value="with">دارای شماره</option><option value="without">بدون شماره</option></select></div>
        <div class="grid grid-cols-2 gap-2 sm:col-span-2 lg:col-span-3 2xl:col-span-6 2xl:justify-self-end"><button type="submit" class="primary"><ui-icon name="search" [size]="16"></ui-icon>جستجو</button><button type="button" (click)="showAll()" class="secondary">مشاهده همه</button></div>
      </form>
      @if (filterError()) {<p role="alert" class="mt-3 rounded-xl bg-danger/10 p-3 text-sm font-bold text-danger">{{ filterError() }}</p>}
    </section>

    <section class="grid grid-cols-1 gap-3 sm:grid-cols-3" aria-label="خلاصه مالی نتایج فیلترشده">
      <div class="summary text-danger"><span>جمع بدهکار</span><strong>{{ money(summary().debit) }}</strong></div>
      <div class="summary text-success"><span>جمع بستانکار</span><strong>{{ money(summary().credit) }}</strong></div>
      <div class="summary text-primary"><span>تراز (بستانکار منهای بدهکار)</span><strong>{{ money(summary().balance) }}</strong><small>این عدد مانده مرجع کیف پول نیست.</small></div>
    </section>

    <section class="card overflow-hidden" aria-labelledby="transaction-list-title">
      <div class="flex flex-col gap-3 border-b border-border p-3 dark:border-slate-700 sm:flex-row sm:items-center sm:justify-between sm:p-5"><h2 id="transaction-list-title" class="text-lg font-extrabold">لیست تراکنش‌ها ({{ number(filteredRows().length) }} رکورد)</h2><div class="flex flex-wrap gap-2"><button type="button" (click)="columnChooserOpen.set(!columnChooserOpen())" class="toolbar"><ui-icon name="sliders" [size]="16"></ui-icon>انتخاب ستون</button><button type="button" (click)="exportRows()" class="toolbar text-success"><ui-icon name="download" [size]="16"></ui-icon>Excel</button></div></div>
      @if (columnChooserOpen()) {<div class="border-b border-border bg-background/60 p-3 dark:border-slate-700 dark:bg-slate-900/30"><div class="flex flex-wrap gap-2">@for (column of columns; track column.id) {<label class="column-choice"><input type="checkbox" [checked]="visible(column.id)" [disabled]="onlyVisible(column.id)" (change)="toggleColumn(column.id, $event)" class="accent-primary">{{ column.label }}</label>}<button type="button" (click)="restoreColumns()" class="px-3 py-2 text-xs font-bold text-primary">بازگردانی ستون‌های پیش‌فرض</button></div></div>}
      <div class="max-h-[58vh] max-w-full overflow-auto">
        <table class="w-full min-w-max text-sm"><thead class="sticky top-0 z-20 bg-background/95 dark:bg-slate-900/95"><tr>@for (column of visibleColumns(); track column.id) {<th class="px-2 py-3 text-right font-bold text-muted" [style.min-width]="column.minWidth"><button type="button" (click)="sort(column.id)" class="flex w-full items-center justify-between gap-2"><span>{{ column.label }}</span><span>{{ sortMark(column.id) }}</span></button></th>}<th class="sticky left-0 min-w-36 bg-background/95 px-2 py-3 text-center font-bold text-muted dark:bg-slate-900/95">عملیات</th></tr><tr>@for (column of visibleColumns(); track column.id) {<th class="px-2 pb-2"><input type="search" [value]="columnSearches()[column.id] || ''" (input)="searchColumn(column.id, value($event))" [attr.aria-label]="'جستجو در ستون ' + column.label" class="h-9 w-full rounded-lg border border-border bg-surface px-2 text-xs outline-none focus:border-primary dark:border-slate-600 dark:bg-slate-800"></th>}<th class="sticky left-0 bg-background/95 dark:bg-slate-900/95"></th></tr></thead>
          <tbody class="divide-y divide-border dark:divide-slate-700">@for (row of pageRows(); track row.id) {<tr class="hover:bg-primary/5">@for (column of visibleColumns(); track column.id) {<td class="px-2 py-3" [style.min-width]="column.minWidth" [attr.dir]="column.ltr ? 'ltr' : null">@if (column.id === 'debit' || column.id === 'credit') { {{ column.value(row) === null ? '—' : money(row.amountRial) }} } @else if (column.id === 'status') {<span [class]="statusClass(row)">{{ row.status === 'success' ? 'موفق' : 'ناموفق' }}</span>} @else { {{ cell(column, row) || '—' }} }</td>}<td class="sticky left-0 bg-surface px-2 py-3 dark:bg-slate-800"><div class="flex justify-center gap-1">@if (row.origin === 'manual') {@if (row.formalInvoiceId) {<button class="op text-primary" type="button" title="مشاهده فاکتور رسمی" (click)="viewInvoice(row)"><ui-icon name="eye" [size]="15"></ui-icon></button><button class="op text-danger" type="button" title="حذف فاکتور رسمی" (click)="requestInvoiceDelete(row)"><ui-icon name="trash-2" [size]="15"></ui-icon></button>} @else {<button class="op text-success" type="button" title="صدور فاکتور رسمی" (click)="requestInvoiceIssue(row)"><ui-icon name="file-text" [size]="15"></ui-icon></button>}} @else if (row.origin === 'wallet-top-up' && row.formalInvoiceId) {<button class="op text-primary" type="button" title="مشاهده فاکتور رسمی" (click)="viewInvoice(row)"><ui-icon name="eye" [size]="15"></ui-icon></button>} @else if (row.origin === 'document-distribution') {<button class="op text-primary" type="button" title="جزئیات رسید داخلی" (click)="openReceipt(row)"><ui-icon name="file-text" [size]="15"></ui-icon></button><button class="op text-primary" type="button" title="دانلود فایل اصلی" (click)="downloadDocument(row)"><ui-icon name="download" [size]="15"></ui-icon></button>}<button class="op text-primary" type="button" title="ارسال پیامک" (click)="openSms(row)"><ui-icon name="message-circle" [size]="15"></ui-icon></button><button class="op text-warning" type="button" title="ورود به حساب کاربری" (click)="accountModal.set(row)"><ui-icon name="log-in" [size]="15"></ui-icon></button></div></td></tr>} @if (!pageRows().length) {<tr><td [attr.colspan]="visibleColumns().length + 1" class="px-4 py-10 text-center font-semibold text-muted">رکوردی مطابق فیلترها پیدا نشد.</td></tr>}</tbody>
        </table>
      </div>
      <div class="flex items-center justify-between gap-3 border-t border-border p-3 text-sm dark:border-slate-700"><span>صفحه {{ number(page()) }} از {{ number(pageCount()) }}</span><div class="flex gap-2"><button class="secondary" type="button" [disabled]="page() <= 1" (click)="page.set(page() - 1)">قبلی</button><button class="secondary" type="button" [disabled]="page() >= pageCount()" (click)="page.set(page() + 1)">بعدی</button></div></div>
    </section>

    @if (manualOpen()) {<div appEscToClose (escPressed)="manualOpen.set(false)" class="modal" (click)="manualOpen.set(false)"><section role="dialog" aria-modal="true" aria-labelledby="manual-title" class="dialog max-w-xl" (click)="$event.stopPropagation()"><div class="dialog-head"><h2 id="manual-title" class="text-lg font-extrabold">تراکنش دستی</h2><button type="button" (click)="manualOpen.set(false)" aria-label="بستن"><ui-icon name="x" [size]="19"></ui-icon></button></div><form class="space-y-4 p-4" (submit)="requestManual($event)"><div><label class="label">کارفرما</label><select [(ngModel)]="manualDraft.employerId" name="employer" class="input"><option value="">انتخاب کارفرما</option>@for (employer of employers(); track employer.id) {<option [value]="employer.id">{{ employer.fullName || employer.mobile }} — {{ employer.companyName }}</option>}</select></div><div><label class="label">مبلغ (ریال)</label><input [(ngModel)]="manualDraft.amountRial" name="amount" inputmode="numeric" class="input" placeholder="مبلغ صحیح و مثبت"></div><div><label class="label">نوع</label><select [(ngModel)]="manualDraft.direction" name="direction" class="input"><option value="debit">بدهکار</option><option value="credit">بستانکار</option></select></div>@if (manualError()) {<p role="alert" class="rounded-xl bg-danger/10 p-3 text-sm font-bold text-danger">{{ manualError() }}</p>}<div class="flex justify-end gap-2"><button type="button" class="secondary" (click)="manualOpen.set(false)">انصراف</button><button type="submit" class="primary">اعمال</button></div></form></section></div>}
    @if (pending(); as action) {<div appEscToClose (escPressed)="pending.set(null)" class="modal" (click)="pending.set(null)"><section role="alertdialog" aria-modal="true" class="dialog max-w-md p-4" (click)="$event.stopPropagation()"><h2 class="text-lg font-extrabold">{{ confirmTitle(action) }}</h2><p class="mt-2 text-sm leading-7 text-muted">{{ confirmMessage(action) }}</p><div class="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" class="secondary" (click)="pending.set(null)">انصراف</button><button type="button" class="primary" [disabled]="submitting()" (click)="confirmAction()">تأیید</button></div></section></div>}
    @if (smsRow()) {<div appEscToClose (escPressed)="smsRow.set(null)" class="modal" (click)="smsRow.set(null)"><section role="dialog" aria-modal="true" class="dialog max-w-lg" (click)="$event.stopPropagation()"><div class="dialog-head"><h2 class="text-lg font-extrabold">ارسال پیامک مستقیم</h2><button type="button" (click)="smsRow.set(null)" aria-label="بستن"><ui-icon name="x" [size]="19"></ui-icon></button></div><div class="space-y-3 p-4"><p class="text-sm text-muted">گیرنده: {{ smsRow()!.fullName }} — <span dir="ltr">{{ smsRow()!.mobile }}</span></p><textarea [(ngModel)]="smsText" rows="4" class="input h-auto py-3" aria-label="متن پیامک"></textarea><button type="button" class="primary" (click)="sendSms()">بررسی ارسال</button></div></section></div>}
    @if (receiptRow(); as row) {<div appEscToClose (escPressed)="receiptRow.set(null)" class="modal" (click)="receiptRow.set(null)"><section role="dialog" aria-modal="true" class="dialog max-w-lg" (click)="$event.stopPropagation()"><div class="dialog-head"><h2 class="text-lg font-extrabold">جزئیات رسید داخلی سند</h2><button type="button" (click)="receiptRow.set(null)" aria-label="بستن"><ui-icon name="x" [size]="19"></ui-icon></button></div>@if (sendFor(row); as send) {@if (receiptFor(send); as receipt) {<dl class="grid grid-cols-2 gap-3 p-4 text-sm"><div><dt>شناسه ارسال</dt><dd>{{ send.id }}</dd></div><div><dt>تاریخ</dt><dd>{{ receipt.issueDate }}</dd></div><div><dt>صفحات</dt><dd>{{ number(receipt.pageCount) }}</dd></div><div><dt>مدت</dt><dd>{{ number(receipt.durationMonths) }} ماه</dd></div><div><dt>هزینه صفحات</dt><dd>{{ money(receipt.breakdown.pageChargeRial) }}</dd></div><div><dt>هزینه پیامک</dt><dd>{{ money(receipt.breakdown.smsChargeRial) }}</dd></div><div class="col-span-2 rounded-xl bg-primary/10 p-3 font-extrabold text-primary"><dt>جمع رسید</dt><dd>{{ money(receipt.breakdown.totalRial) }}</dd></div></dl>}} @else {<p class="p-4 text-sm text-muted">رسید مرتبط در دسترس نیست.</p>}</section></div>}
    @if (accountModal()) {<div appEscToClose (escPressed)="accountModal.set(null)" class="modal" (click)="accountModal.set(null)"><section role="dialog" aria-modal="true" class="dialog max-w-md p-4" (click)="$event.stopPropagation()"><h2 class="text-lg font-extrabold">ورود به حساب کاربری</h2><p class="mt-2 text-sm leading-7 text-muted">ورود امن به حساب کاربر به قرارداد احراز هویت و ثبت رویداد نیاز دارد و در این پیش‌نمایش اجرا نمی‌شود. هیچ نشست یا توکنی تغییر نکرد.</p><button type="button" class="secondary mt-4" (click)="accountModal.set(null)">بستن</button></section></div>}
  </div>`,
  styles: [`
    .card{border:1px solid rgb(var(--color-border));border-radius:1rem;background:rgb(var(--color-surface));color:rgb(var(--color-foreground));box-shadow:0 1px 3px rgb(15 23 42/.08)}.label{display:block;margin-bottom:.375rem;font-size:.8rem;font-weight:700}.input{width:100%;min-height:2.75rem;border:1px solid rgb(var(--color-border));border-radius:.75rem;padding-inline:.75rem;color:rgb(var(--color-foreground));background:rgb(var(--color-background));outline:none}.input:focus{border-color:rgb(var(--color-primary));box-shadow:0 0 0 2px rgb(var(--color-primary)/.15)}.primary,.secondary,.toolbar{display:inline-flex;min-height:2.5rem;align-items:center;justify-content:center;gap:.4rem;border-radius:.75rem;padding-inline:.85rem;font-size:.8rem;font-weight:700}.primary{background:rgb(var(--color-primary));color:white}.secondary,.toolbar{border:1px solid rgb(var(--color-border))}.primary:disabled,.secondary:disabled{opacity:.45}.summary{display:flex;min-height:6.5rem;flex-direction:column;justify-content:center;border:1px solid rgb(var(--color-border));border-radius:1rem;padding:1rem;background:rgb(var(--color-surface));box-shadow:0 1px 3px rgb(15 23 42/.08)}.summary span{font-size:.8rem;font-weight:700}.summary strong{margin-top:.35rem;font-size:1.1rem}.summary small{margin-top:.25rem;color:rgb(var(--color-muted));font-size:.7rem}.column-choice{display:flex;align-items:center;gap:.5rem;border:1px solid rgb(var(--color-border));border-radius:.5rem;padding:.5rem .75rem;font-size:.75rem;font-weight:700;background:rgb(var(--color-surface))}.op{display:inline-flex;height:2rem;width:2rem;align-items:center;justify-content:center;border:1px solid currentColor;border-radius:.5rem}.modal{position:fixed;inset:0;z-index:60;display:flex;align-items:center;justify-content:center;background:rgb(0 0 0/.6);padding:.75rem;backdrop-filter:blur(4px)}.dialog{width:100%;max-height:calc(100vh - 1.5rem);overflow:auto;border:1px solid rgb(var(--color-border));border-radius:1rem;background:rgb(var(--color-surface));color:rgb(var(--color-foreground));box-shadow:0 20px 50px rgb(0 0 0/.25)}.dialog-head{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgb(var(--color-border));padding:1rem}.dialog dt{font-size:.75rem;color:rgb(var(--color-muted))}.dialog dd{margin-top:.25rem;font-weight:700}@media(max-width:420px){.summary{min-height:5.5rem}.modal{align-items:flex-end}.dialog{border-bottom-left-radius:0;border-bottom-right-radius:0}}
  `]
})
export class InternalTransactionsComponent {
  private readonly wallets = inject(Fish24WalletPreviewService); private readonly transactions = inject(Fish24TransactionPreviewService);
  private readonly distribution = inject(Fish24DocumentDistributionPreviewService); private readonly users = inject(BusinessUserPreviewService);
  private readonly preferences = inject(InternalListPreferencesService); private readonly xlsx = inject(PlainXlsxService);
  private readonly toast = inject(ToastService); private readonly router = inject(Router);
  private readonly restored = this.preferences.loadFilters(LIST_ID, FILTER_DEFAULTS, validateStoredFilters);
  readonly columns = COLUMNS; readonly defaultColumns = COLUMNS.map(column => column.id);
  readonly selectedColumns = signal<readonly string[]>(this.preferences.load(LIST_ID, this.defaultColumns, this.defaultColumns));
  readonly visibleColumns = computed(() => this.columns.filter(column => this.selectedColumns().includes(column.id)));
  readonly columnSearches = signal<InternalListColumnSearches>({}); readonly tableSort = signal<InternalListSort>({ columnId: null, direction: null });
  readonly columnChooserOpen = signal(false); readonly filterError = signal(''); readonly applied = signal<TransactionFilters>(this.restored);
  draft: TransactionFilters = { ...this.restored }; readonly page = signal(1); readonly pageSize = 10;
  readonly employers = computed(() => this.users.users().filter(user => user.roles.includes('employer')));
  readonly filteredRows = computed(() => this.wallets.transactions().filter(row => this.matches(row, this.applied())));
  readonly summary = computed(() => this.filteredRows().filter(row => row.status === 'success').reduce((total, row) => row.direction === 'debit' ? { ...total, debit: total.debit + row.amountRial, balance: total.balance - row.amountRial } : { ...total, credit: total.credit + row.amountRial, balance: total.balance + row.amountRial }, { debit: 0, credit: 0, balance: 0 }));
  readonly tableRows = computed(() => sortInternalListRows(filterByInternalListColumns(this.filteredRows(), this.columns, this.selectedColumns(), this.columnSearches()), this.columns, this.tableSort()));
  readonly pageCount = computed(() => Math.max(1, Math.ceil(this.tableRows().length / this.pageSize)));
  readonly pageRows = computed(() => { const page = Math.min(this.page(), this.pageCount()); return this.tableRows().slice((page - 1) * this.pageSize, page * this.pageSize); });
  readonly manualOpen = signal(false); readonly manualError = signal(''); manualDraft: ManualDraft = { employerId: '', amountRial: '', direction: 'debit' };
  private manualRequestId = ''; readonly pending = signal<PendingAction | null>(null); readonly submitting = signal(false);
  readonly smsRow = signal<Fish24WalletTransaction | null>(null); smsText = ''; readonly receiptRow = signal<Fish24WalletTransaction | null>(null); readonly accountModal = signal<Fish24WalletTransaction | null>(null);

  applyFilters(event: Event): void { event.preventDefault(); const normalized = validateStoredFilters(this.draft)!; if (!this.validDraftAmounts() || (this.draft.fromTimestamp && !storedTimestamp(this.draft.fromTimestamp)) || (this.draft.toTimestamp && !storedTimestamp(this.draft.toTimestamp, true))) { this.filterError.set('مبلغ یا تاریخ واردشده معتبر نیست.'); return; } if (normalized.fromTimestamp && normalized.toTimestamp && normalized.fromTimestamp > normalized.toTimestamp) { this.filterError.set('بازه تاریخ و ساعت معتبر نیست.'); return; } this.filterError.set(''); this.draft = { ...normalized }; this.applied.set(normalized); this.preferences.saveFilters(LIST_ID, normalized); this.page.set(1); }
  showAll(): void { this.draft = { ...FILTER_DEFAULTS }; this.applied.set(FILTER_DEFAULTS); this.preferences.resetFilters(LIST_ID); this.filterError.set(''); this.page.set(1); }
  visible(id: string): boolean { return this.selectedColumns().includes(id); } onlyVisible(id: string): boolean { return this.visible(id) && this.selectedColumns().length === 1; }
  toggleColumn(id: string, event: Event): void { const checked = (event.target as HTMLInputElement).checked; const next = checked ? [...this.selectedColumns(), id] : this.selectedColumns().filter(item => item !== id); if (!next.length) return; this.selectedColumns.set(this.preferences.save(LIST_ID, next, this.defaultColumns)); if (!checked) this.searchColumn(id, ''); }
  restoreColumns(): void { this.selectedColumns.set(this.preferences.reset(LIST_ID, this.defaultColumns, this.defaultColumns)); this.columnSearches.set({}); this.tableSort.set({ columnId: null, direction: null }); }
  searchColumn(id: string, query: string): void { this.columnSearches.update(searches => ({ ...searches, [id]: query })); this.page.set(1); }
  sort(id: string): void { this.tableSort.update(current => nextInternalListSort(current, id)); this.page.set(1); } sortMark(id: string): string { const sort = this.tableSort(); return sort.columnId !== id ? '↕' : sort.direction === 'asc' ? '↑' : '↓'; }
  value(event: Event): string { return (event.target as HTMLInputElement).value; } cell(column: InternalListColumn<Fish24WalletTransaction>, row: Fish24WalletTransaction): string { return String(column.value(row) ?? ''); }
  statusClass(row: Fish24WalletTransaction): string { return `inline-flex rounded-full px-2 py-1 text-xs font-bold ${row.status === 'success' ? 'bg-success/15 text-success' : 'bg-danger/15 text-danger'}`; }
  money(value: number): string { return `${new Intl.NumberFormat('fa-IR').format(value)} ریال`; } number(value: number): string { return new Intl.NumberFormat('fa-IR').format(value); }
  exportRows(): void { const columns = this.visibleColumns(); const rows = this.filteredRows().map(row => columns.map(column => column.exportValue ? column.exportValue(row) : column.value(row) == null ? null : String(column.value(row)))); this.xlsx.export('fish24-transactions.xlsx', columns.map(column => column.label), rows); this.toast.show(`${this.number(rows.length)} رکورد فیلترشده برای Excel آماده شد.`, 'success'); }
  openManual(): void { this.manualDraft = { employerId: '', amountRial: '', direction: 'debit' }; this.manualError.set(''); this.manualRequestId = this.newRequestId(); this.manualOpen.set(true); }
  requestManual(event: Event): void { event.preventDefault(); if (!this.employers().some(user => String(user.id) === this.manualDraft.employerId)) { this.manualError.set('کارفرما را انتخاب کنید.'); return; } if (parsePositiveRialAmount(this.manualDraft.amountRial) === null) { this.manualError.set('مبلغ باید عدد صحیح و مثبت به ریال باشد.'); return; } this.manualError.set(''); this.pending.set({ kind: 'manual' }); }
  requestInvoiceIssue(row: Fish24WalletTransaction): void { this.pending.set({ kind: 'issue-invoice', transactionId: row.id }); }
  requestInvoiceDelete(row: Fish24WalletTransaction): void { this.pending.set({ kind: 'delete-invoice', transactionId: row.id }); }
  confirmTitle(action: PendingAction): string { return action.kind === 'manual' ? 'تأیید تراکنش دستی' : action.kind === 'issue-invoice' ? 'تأیید صدور فاکتور رسمی' : 'تأیید حذف فاکتور رسمی'; }
  confirmMessage(action: PendingAction): string { if (action.kind === 'manual') return `مبلغ ${this.money(parsePositiveRialAmount(this.manualDraft.amountRial) ?? 0)} در کیف پول کارفرما ${this.manualDraft.direction === 'debit' ? 'کسر' : 'افزوده'} می‌شود. آیا ادامه می‌دهید؟`; return action.kind === 'issue-invoice' ? 'فاکتور رسمی بر پایه مبلغ اصلی تراکنش و تنظیم VAT تاریخ صدور ایجاد می‌شود. اصل تراکنش و مانده کیف پول تغییر نمی‌کند.' : 'فقط ارتباط فاکتور رسمی حذف می‌شود. تراکنش، پرداخت و مانده کیف پول بدون تغییر می‌مانند.'; }
  confirmAction(): void { const action = this.pending(); if (!action || this.submitting()) return; this.submitting.set(true); try { if (action.kind === 'manual') this.createManual(); else if (action.kind === 'issue-invoice') this.issueInvoice(action.transactionId!); else this.deleteInvoice(action.transactionId!); } finally { this.pending.set(null); this.submitting.set(false); } }
  viewInvoice(row: Fish24WalletTransaction): void { if (row.formalInvoiceId) void this.router.navigate(['/fish24/employer/invoices', row.formalInvoiceId, 'print']); }
  openSms(row: Fish24WalletTransaction): void { this.smsText = ''; this.smsRow.set(row); }
  sendSms(): void { if (!this.smsText.trim()) { this.toast.show('متن پیامک نمی‌تواند خالی باشد.', 'error'); return; } this.toast.show('ارسال واقعی انجام نشد؛ پیامک مستقیم فقط در پیش‌نمایش بررسی شد.', 'success'); this.smsRow.set(null); }
  sendFor(row: Fish24WalletTransaction): Fish24DocumentSend | null { return row.origin === 'document-distribution' ? this.distribution.findSend(row.operationId) : null; }
  receiptFor(send: Fish24DocumentSend) { return this.distribution.receiptFor(send.id); }
  openReceipt(row: Fish24WalletTransaction): void { this.receiptRow.set(row); }
  downloadDocument(row: Fish24WalletTransaction): void { const send = this.sendFor(row); if (!send?.sourceFile) { this.toast.show('فایل اصلی این سند در وضعیت نمایشی در دسترس نیست.', 'error'); return; } const url = URL.createObjectURL(send.sourceFile); const anchor = document.createElement('a'); anchor.href = url; anchor.download = send.sourceFileName; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 0); }

  private createManual(): void { const employer = this.employers().find(user => String(user.id) === this.manualDraft.employerId); if (!employer) return; const result = this.transactions.createManualTransaction({ requestId: this.manualRequestId, employerId: String(employer.id), mobile: employer.mobile, fullName: employer.fullName ?? '', companyName: employer.companyName, workplaceName: employer.companyName, userType: employer.userType, amountRial: this.manualDraft.amountRial, direction: this.manualDraft.direction, createdAt: this.currentTimestamp() }); if (!result.ok) { this.manualError.set(result.error === 'insufficient-funds' ? 'موجودی کیف پول کافی نیست؛ هیچ تغییری اعمال نشد.' : result.error === 'forbidden' ? 'دسترسی انجام تراکنش مالی وجود ندارد.' : 'تراکنش انجام نشد.'); this.toast.show(this.manualError(), 'error'); return; } this.manualOpen.set(false); this.toast.show(result.existing ? 'این درخواست قبلاً ثبت شده و دوباره اعمال نشد.' : 'تراکنش دستی و مانده کیف پول ثبت شد.', 'success'); }
  private issueInvoice(transactionId: string): void { const result = this.transactions.issueFormalInvoice(transactionId); if (!result.ok) { this.toast.show('صدور فاکتور رسمی انجام نشد.', 'error'); return; } this.toast.show(result.existing ? 'فاکتور این تراکنش قبلاً صادر شده است.' : 'فاکتور رسمی صادر شد؛ تراکنش و کیف پول تغییر نکردند.', 'success'); }
  private deleteInvoice(transactionId: string): void { const result = this.transactions.deleteFormalInvoice(transactionId); if (!result.ok) { this.toast.show('حذف فاکتور رسمی انجام نشد.', 'error'); return; } this.toast.show('فقط فاکتور رسمی حذف شد؛ تراکنش و کیف پول تغییر نکردند.', 'success'); }
  private matches(row: Fish24WalletTransaction, filter: TransactionFilters): boolean { const amount = filter.amount ? Number(filter.amount) : null; const debit = filter.exactDebit ? Number(filter.exactDebit) : null; const credit = filter.exactCredit ? Number(filter.exactCredit) : null; return (!filter.name || row.fullName.includes(filter.name)) && (!filter.mobile || row.mobile.includes(filter.mobile)) && (!filter.company || row.companyName.includes(filter.company)) && (amount === null || row.amountRial === amount) && (!filter.trackingCode || row.trackingCode.includes(filter.trackingCode)) && (filter.status === 'all' || row.status === filter.status) && (!filter.fromTimestamp || row.createdAt >= filter.fromTimestamp) && (!filter.toTimestamp || row.createdAt <= filter.toTimestamp) && (filter.direction === 'all' || row.direction === filter.direction) && (debit === null || row.direction === 'debit' && row.amountRial === debit) && (credit === null || row.direction === 'credit' && row.amountRial === credit) && (filter.invoice === 'all' || (filter.invoice === 'with') === Boolean(row.formalInvoiceNumber)); }
  private validDraftAmounts(): boolean { return [this.draft.amount, this.draft.exactDebit, this.draft.exactCredit].every(value => !value || parsePositiveRialAmount(value) !== null); }
  private newRequestId(): string { return `manual-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; }
  private currentTimestamp(): string { const parts = new Intl.DateTimeFormat('fa-IR-u-ca-persian-nu-latn', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }).formatToParts(new Date()); const value = (type: Intl.DateTimeFormatPartTypes) => parts.find(part => part.type === type)?.value ?? ''; return `${value('year')}/${value('month')}/${value('day')} ${value('hour')}:${value('minute')}`; }
}
