import { TestBed } from '@angular/core/testing';
import { Fish24TicketPreviewService, TICKET_MAX_FILE_BYTES } from './fish24-ticket-preview.service';

describe('Fish24TicketPreviewService', () => {
  let service: Fish24TicketPreviewService;
  beforeEach(() => { TestBed.resetTestingModule(); service = TestBed.inject(Fish24TicketPreviewService); });
  const file = (name='proof.pdf', bytes=[1,2,3]) => new File([new Uint8Array(bytes)], name, { type: 'application/pdf' });
  const create = () => service.createTicketFromDocument(2006, 'user-1', 'support', 'درخواست جدید', [file()], 'create-1')!;

  it('shows employer creation in the shared internal list while preserving ownership', () => { const id=create(); expect(service.findInternalTicket(id,'support-expert')?.ownerEmployerId).toBe('user-1'); expect(service.findEmployerTicket(id,'user-1')).toBeTruthy(); expect(service.findEmployerTicket(id,'1001')).toBeUndefined(); });
  it('lets every internal role view tickets across departments', () => { for(const role of ['super-admin','sales-expert','support-expert'] as const) expect(service.internalTickets(role).length).toBe(3); expect(service.internalTickets('employer')).toEqual([]); });
  it('internal reply is visible to employer and sets answered status', () => { const id=create(); expect(service.internalReply(id,'sales-expert','کارشناس','پاسخ داخلی',[],'internal-1').ok).toBeTrue(); const ticket=service.findEmployerTicket(id,'user-1')!; expect(ticket.status).toBe('جواب داده شده'); expect(ticket.messages.at(-1)?.text).toBe('پاسخ داخلی'); });
  it('employer reply returns status to needs review', () => { const id=create(); service.internalReply(id,'support-expert','پشتیبان','پاسخ',[],'i1'); service.employerReply(id,'user-1','پیگیری',[],'e1'); expect(service.findTicket(id)?.status).toBe('نیاز به بررسی'); });
  it('viewing changes neither status nor timestamps', () => { const before=service.findTicket(3001)!; service.findInternalTicket(3001,'support-expert'); service.findEmployerTicket(3001,'1001'); expect(service.findTicket(3001)?.status).toBe(before.status); expect(service.findTicket(3001)?.updatedAt).toBe(before.updatedAt); });
  it('closes and reopens from both access scopes and rejects closed replies', () => { const id=create(); expect(service.closeForEmployer(id,'user-1').ok).toBeTrue(); expect(service.internalReply(id,'support-expert','پشتیبان','نشد',[],'closed').error).toBe('closed'); expect(service.reopenInternal(id,'sales-expert').ok).toBeTrue(); expect(service.findTicket(id)?.status).toBe('نیاز به بررسی'); expect(service.closeInternal(id,'super-admin').ok).toBeTrue(); expect(service.reopenForEmployer(id,'user-1').ok).toBeTrue(); });
  it('refers an open ticket, audits it internally, and rejects unchanged or closed referral', () => { const id=create(); expect(service.refer(id,'support-expert','sales','علی').ok).toBeTrue(); const ticket=service.findTicket(id)!; expect(ticket.recipientDepartment).toBe('sales'); expect(ticket.status).toBe('نیاز به بررسی'); expect(ticket.referrals.length).toBe(1); expect(service.refer(id,'sales-expert','sales','علی').error).toBe('unchanged'); service.closeInternal(id,'super-admin'); expect(service.refer(id,'support-expert','management','علی').error).toBe('closed'); });
  it('does not expose internal referral history through an employer conversation projection', () => { const id=create(); service.refer(id,'support-expert','sales','پشتیبان'); const employer=service.findEmployerTicket(id,'user-1')!; expect(employer.messages.some(message=>message.text.includes('ارجاع'))).toBeFalse(); expect('referrals' in employer).toBeFalse(); });
  it('requires text and rejects attachment-only or whitespace replies', () => { const id=create(); expect(service.employerReply(id,'user-1','   ',[file()],'blank').error).toBe('empty'); expect(service.findTicket(id)?.messages.length).toBe(1); });
  it('validates file count, type and size', () => { expect(service.validateAttachments(Array.from({length:6},(_,i)=>file(`${i}.pdf`)))).toContain('حداکثر'); expect(service.validateAttachments([file('bad.exe')])).toContain('نوع فایل'); expect(service.validateAttachments([new File([new Uint8Array(TICKET_MAX_FILE_BYTES+1)],'big.zip')])).toContain('۱۰ مگابایت'); });
  it('retains exact attachment bytes and associates them with the owning message', async () => { const id=create(); const ticket=service.findTicket(id)!; const attachment=ticket.messages[0].attachments[0]; const blob=service.attachmentBlob(id,ticket.messages[0].id,attachment.id,{ownerId:'user-1'})!; expect(Array.from(new Uint8Array(await blob.arrayBuffer()))).toEqual([1,2,3]); expect(service.attachmentBlob(id,ticket.messages[0].id,attachment.id,{ownerId:'1001'})).toBeNull(); });
  it('prevents duplicate submission handling but permits later identical text', () => { const id=create(); expect(service.employerReply(id,'user-1','یکسان',[],'same').ok).toBeTrue(); expect(service.employerReply(id,'user-1','یکسان',[],'same').error).toBe('duplicate'); expect(service.employerReply(id,'user-1','یکسان',[],'later').ok).toBeTrue(); });
  it('keeps badge independent and enforces Excel roles', () => { const before=service.needsReviewCount(); const id=create(); expect(service.needsReviewCount()).toBe(before+1); service.closeInternal(id,'support-expert'); expect(service.needsReviewCount()).toBe(before); expect(service.canExport('super-admin')).toBeTrue(); expect(service.canExport('sales-expert')).toBeTrue(); expect(service.canExport('support-expert')).toBeFalse(); });
});
