import { Injectable, computed, inject, signal } from '@angular/core';
import { Fish24DocumentDistributionPreviewService } from '../financial/fish24-document-distribution-preview.service';
import { Fish24RoleId } from '../models/fish24-role.model';

export type Fish24TicketStatus = 'نیاز به بررسی' | 'جواب داده شده' | 'بسته شده';
export type Fish24TicketDepartment = 'management' | 'sales' | 'support';
export type Fish24TicketActorSide = 'employer' | 'internal';
export type EmployerTicketStatus = Fish24TicketStatus;
export type EmployerTicketOrigin = 'employerToSystem' | 'employeeToEmployer';
export type EmployerDocumentDistributionStatus = 'توزیع‌شده' | 'توزیع‌نشده';
export type EmployerDocumentHostingLabel = '1 ماهه' | '3 ماهه' | '6 ماهه' | '12 ماهه' | 'منقضی';
export const FISH24_TICKET_DEPARTMENTS: readonly { id: Fish24TicketDepartment; label: string }[] = [{ id: 'management', label: 'مدیریت' }, { id: 'sales', label: 'فروش' }, { id: 'support', label: 'پشتیبانی' }];
export const TICKET_ALLOWED_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'zip'] as const;
export const TICKET_MAX_FILES = 5;
export const TICKET_MAX_FILE_BYTES = 10 * 1024 * 1024;
export const FISH24_DEMO_TICKET_ID = 3004;
export const FISH24_DEMO_EMPLOYER_ID = 'user-1';
export const FISH24_DEMO_ATTACHMENT_BYTES = new TextEncoder().encode('%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [] /Count 0 >>\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF\n');

export interface Fish24TicketAttachment { readonly id: number; readonly name: string; readonly size: number; readonly type: string; readonly blob: Blob; }
export interface EmployerTicketMessage { readonly id: number; readonly authorName: string; readonly authorRole: string; readonly senderDisplay: string; readonly senderSide: Fish24TicketActorSide; readonly sentAt: string; readonly text: string; readonly attachments: readonly Fish24TicketAttachment[]; }
export interface Fish24TicketReferral { readonly id: number; readonly from: Fish24TicketDepartment; readonly to: Fish24TicketDepartment; readonly referredBy: string; readonly referredAt: string; }
export interface EmployerTicketRecord { readonly id: number; readonly ownerEmployerId: string; readonly employerName: string; readonly employerMobile: string; readonly companyName: string | null; readonly subject: string; readonly workplace: string; readonly origin: EmployerTicketOrigin; readonly status: Fish24TicketStatus; readonly createdAt: string; readonly updatedAt: string; readonly recipientDepartment: Fish24TicketDepartment; readonly employeeName?: string | null; readonly employeeMobile?: string | null; readonly messages: readonly EmployerTicketMessage[]; readonly referrals: readonly Fish24TicketReferral[]; }
export type EmployerTicketPublicRecord = Omit<EmployerTicketRecord, 'referrals'>;
export interface EmployerDocumentRecord { readonly id: number; readonly sentAt: string; readonly title: string; readonly companyId: number; readonly companyName: string; readonly amountRial: number; readonly status: EmployerDocumentDistributionStatus; readonly hostingLabel: EmployerDocumentHostingLabel; readonly expiresAt: string; readonly isLocked: boolean; readonly employerId: string; readonly employerName: string; readonly employerMobile: string; }
export interface TicketMutationResult { readonly ok: boolean; readonly error?: 'not-found' | 'forbidden' | 'closed' | 'empty' | 'duplicate' | 'unchanged' | 'invalid-attachments'; }

const INTERNAL_ROLES: readonly Fish24RoleId[] = ['super-admin', 'sales-expert', 'support-expert'];
const msg = (id: number, authorName: string, authorRole: string, senderSide: Fish24TicketActorSide, sentAt: string, text: string): EmployerTicketMessage => ({ id, authorName, authorRole, senderDisplay: authorName, senderSide, sentAt, text, attachments: [] });
const demoSupportReply: EmployerTicketMessage = { id: 6, authorName: 'کارشناس پشتیبانی', authorRole: 'پشتیبانی', senderDisplay: 'کارشناس پشتیبانی', senderSide: 'internal', sentAt: '1405/06/18 12:15', text: 'درخواست شما بررسی شد. راهنمای نمونه برای مشاهده و دانلود به پاسخ پیوست شده است.', attachments: [{ id: 1, name: 'fish24-demo-support-reply.pdf', size: FISH24_DEMO_ATTACHMENT_BYTES.byteLength, type: 'application/pdf', blob: new Blob([FISH24_DEMO_ATTACHMENT_BYTES], { type: 'application/pdf' }) }] };

@Injectable({ providedIn: 'root' })
export class Fish24TicketPreviewService {
  private readonly distribution = inject(Fish24DocumentDistributionPreviewService);
  private nextTicketId = 3100; private nextMessageId = 100; private nextAttachmentId = 10; private nextReferralId = 1;
  private readonly handledSubmissions = new Set<string>();
  private readonly state = signal<readonly EmployerTicketRecord[]>([
    { id: 3001, ownerEmployerId: '1001', employerName: 'مریم احمدی', employerMobile: '09121234567', companyName: 'مجموعه نمونه سپهر', subject: 'فیش حقوق مرداد ۱۴۰۵', workplace: 'مجموعه نمونه سپهر', origin: 'employerToSystem', status: 'نیاز به بررسی', createdAt: '1405/06/16 09:45', updatedAt: '1405/06/16 10:20', recipientDepartment: 'support', employeeName: null, employeeMobile: null, messages: [msg(1, 'مریم احمدی', 'کارفرما', 'employer', '1405/06/16 09:45', 'لطفاً وضعیت سند ارسالی را بررسی کنید.')], referrals: [] },
    { id: 3002, ownerEmployerId: '1002', employerName: 'رضا کریمی', employerMobile: '09129876543', companyName: 'مجموعه آزمایشی باران', subject: 'گواهی پرداخت پاداش', workplace: 'مجموعه آزمایشی باران', origin: 'employerToSystem', status: 'جواب داده شده', createdAt: '1405/05/30 11:05', updatedAt: '1405/05/30 14:10', recipientDepartment: 'sales', employeeName: null, employeeMobile: null, messages: [msg(2, 'رضا کریمی', 'کارفرما', 'employer', '1405/05/30 11:05', 'لطفاً نتیجه پردازش این سند را بررسی کنید.'), msg(3, 'کارشناس فروش', 'فروش', 'internal', '1405/05/30 14:10', 'بررسی انجام شد و نتیجه در پنل قابل مشاهده است.')], referrals: [] },
    { id: 3003, ownerEmployerId: 'user-1', employerName: 'علی احمدی', employerMobile: '09123456789', companyName: 'مجموعه نمایشی نارنج', subject: 'پیش‌نمایش پرداخت شهریور', workplace: 'مجموعه نمایشی نارنج', origin: 'employerToSystem', status: 'بسته شده', createdAt: '1405/06/12 08:40', updatedAt: '1405/06/12 16:25', recipientDepartment: 'management', employeeName: null, employeeMobile: null, messages: [msg(4, 'علی احمدی', 'کارفرما', 'employer', '1405/06/12 08:40', 'لطفاً جزئیات این سند را بررسی کنید.')], referrals: [] },
    { id: FISH24_DEMO_TICKET_ID, ownerEmployerId: FISH24_DEMO_EMPLOYER_ID, employerName: 'علی احمدی', employerMobile: '09123456789', companyName: 'مجموعه نمایشی نارنج', subject: 'راهنمای دریافت سند ارسالی', workplace: 'مجموعه نمایشی نارنج', origin: 'employerToSystem', status: 'جواب داده شده', createdAt: '1405/06/18 10:30', updatedAt: '1405/06/18 12:15', recipientDepartment: 'support', employeeName: null, employeeMobile: null, messages: [msg(5, 'علی احمدی', 'کارفرما', 'employer', '1405/06/18 10:30', 'لطفاً درباره نحوه دریافت و مشاهده سند ارسالی راهنمایی کنید.'), demoSupportReply], referrals: [] }
  ]);
  readonly tickets = this.state.asReadonly();
  readonly needsReviewCount = computed(() => this.state().filter(ticket => ticket.status === 'نیاز به بررسی').length);
  readonly documents = computed<readonly EmployerDocumentRecord[]>(() => this.distribution.sends().map(send => ({ id: Number(send.id), sentAt: send.createdAt, title: send.title, companyId: send.companyId, companyName: send.companyName, employerId: send.employerId, employerName: send.employerName, employerMobile: send.employerMobile, amountRial: this.distribution.receiptFor(send.id)?.breakdown.totalRial ?? 0, status: send.isPaid ? 'توزیع‌شده' : 'توزیع‌نشده', hostingLabel: send.expiresAt < '1405/06/23' ? 'منقضی' : `${send.durationMonths} ماهه` as EmployerDocumentHostingLabel, expiresAt: send.expiresAt, isLocked: !send.employeeAccessActive })));

  internalTickets(role: Fish24RoleId): readonly EmployerTicketRecord[] { return this.isInternal(role) ? this.state() : []; }
  employerTickets(ownerId: string): readonly EmployerTicketPublicRecord[] { return this.state().filter(ticket => ticket.ownerEmployerId === ownerId).map(ticket => this.employerProjection(ticket)); }
  answeredCountForEmployer(ownerId: string): number { return this.state().filter(ticket => ticket.ownerEmployerId === ownerId && ticket.status === 'جواب داده شده').length; }
  findDocument(id: number): EmployerDocumentRecord | undefined { return this.documents().find(document => document.id === id); }
  findTicket(id: number): EmployerTicketRecord | undefined { return this.state().find(ticket => ticket.id === id); }
  findInternalTicket(id: number, role: Fish24RoleId): EmployerTicketRecord | undefined { return this.isInternal(role) ? this.findTicket(id) : undefined; }
  findEmployerTicket(id: number, ownerId: string): EmployerTicketPublicRecord | undefined { const ticket = this.state().find(item => item.id === id && item.ownerEmployerId === ownerId); return ticket ? this.employerProjection(ticket) : undefined; }
  departmentLabel(id: Fish24TicketDepartment): string { return FISH24_TICKET_DEPARTMENTS.find(item => item.id === id)?.label ?? id; }
  toggleDocumentLock(id: number): void { const send = this.distribution.findSend(String(id)); if (send) this.distribution.setEmployeeAccess(send.id, !send.employeeAccessActive); }
  deleteUndistributedDocument(id: number): void { this.distribution.deleteUnpaid(String(id)); }
  previewDistributeDocument(id: number): void { this.distribution.confirmPayment(String(id)); }
  validateAttachments(files: readonly File[]): string | null { if (files.length > TICKET_MAX_FILES) return `حداکثر ${TICKET_MAX_FILES} فایل مجاز است.`; for (const file of files) { const extension = file.name.split('.').pop()?.toLowerCase() ?? ''; if (!TICKET_ALLOWED_EXTENSIONS.includes(extension as never)) return `نوع فایل «${file.name}» مجاز نیست.`; if (file.size > TICKET_MAX_FILE_BYTES) return `حجم فایل «${file.name}» بیشتر از ۱۰ مگابایت است.`; } return null; }
  createTicketFromDocument(documentId: number, ownerId: string, department: Fish24TicketDepartment, request: string, files: readonly File[], submissionKey: string): number | null { const document = this.findDocument(documentId); const text = request.trim(); if (!document || document.employerId !== ownerId || !text || !this.validDepartment(department) || this.validateAttachments(files) || !this.claim(submissionKey)) return null; const timestamp = this.now(); const id = this.nextTicketId++; const ticket: EmployerTicketRecord = { id, ownerEmployerId: ownerId, employerName: document.employerName, employerMobile: document.employerMobile, companyName: document.companyName || null, subject: document.title, workplace: document.companyName, origin: 'employerToSystem', status: 'نیاز به بررسی', createdAt: timestamp, updatedAt: timestamp, recipientDepartment: department, employeeName: null, employeeMobile: null, messages: [this.message(document.employerName, 'کارفرما', 'employer', text, files, timestamp)], referrals: [] }; this.state.update(items => [ticket, ...items]); return id; }
  employerReply(id: number, ownerId: string, text: string, files: readonly File[], key: string): TicketMutationResult { return this.reply(id, text, files, key, ticket => ticket.ownerEmployerId === ownerId, ticket => ({ ...ticket, status: 'نیاز به بررسی' }), ticket => this.message(ticket.employerName, 'کارفرما', 'employer', text.trim(), files)); }
  internalReply(id: number, role: Fish24RoleId, author: string, text: string, files: readonly File[], key: string): TicketMutationResult { return this.reply(id, text, files, key, () => this.isInternal(role), ticket => ({ ...ticket, status: 'جواب داده شده' }), () => this.message(author, this.internalRoleLabel(role), 'internal', text.trim(), files)); }
  closeForEmployer(id: number, ownerId: string): TicketMutationResult { return this.mutate(id, ticket => ticket.ownerEmployerId === ownerId, ticket => ticket.status === 'بسته شده' ? ticket : ({ ...ticket, status: 'بسته شده', updatedAt: this.now() })); }
  reopenForEmployer(id: number, ownerId: string): TicketMutationResult { return this.mutate(id, ticket => ticket.ownerEmployerId === ownerId, ticket => ticket.status !== 'بسته شده' ? ticket : ({ ...ticket, status: 'نیاز به بررسی', updatedAt: this.now() })); }
  closeInternal(id: number, role: Fish24RoleId): TicketMutationResult { return this.mutate(id, () => this.isInternal(role), ticket => ticket.status === 'بسته شده' ? ticket : ({ ...ticket, status: 'بسته شده', updatedAt: this.now() })); }
  reopenInternal(id: number, role: Fish24RoleId): TicketMutationResult { return this.mutate(id, () => this.isInternal(role), ticket => ticket.status !== 'بسته شده' ? ticket : ({ ...ticket, status: 'نیاز به بررسی', updatedAt: this.now() })); }
  refer(id: number, role: Fish24RoleId, to: Fish24TicketDepartment, author: string): TicketMutationResult { const ticket = this.findInternalTicket(id, role); if (!ticket) return { ok: false, error: 'forbidden' }; if (ticket.status === 'بسته شده') return { ok: false, error: 'closed' }; if (ticket.recipientDepartment === to) return { ok: false, error: 'unchanged' }; const timestamp = this.now(); const referral: Fish24TicketReferral = { id: this.nextReferralId++, from: ticket.recipientDepartment, to, referredBy: author, referredAt: timestamp }; this.state.update(items => items.map(item => item.id === id ? { ...item, recipientDepartment: to, status: 'نیاز به بررسی', updatedAt: timestamp, referrals: [...item.referrals, referral] } : item)); return { ok: true }; }
  attachmentBlob(ticketId: number, messageId: number, attachmentId: number, access: { ownerId?: string; role?: Fish24RoleId }): Blob | null { const ticket = access.role ? this.findInternalTicket(ticketId, access.role) : this.findEmployerTicket(ticketId, access.ownerId ?? ''); return ticket?.messages.find(message => message.id === messageId)?.attachments.find(file => file.id === attachmentId)?.blob ?? null; }
  canExport(role: Fish24RoleId): boolean { return role === 'super-admin' || role === 'sales-expert'; }
  private reply(id: number, text: string, files: readonly File[], key: string, allowed: (ticket: EmployerTicketRecord) => boolean, status: (ticket: EmployerTicketRecord) => EmployerTicketRecord, build: (ticket: EmployerTicketRecord) => EmployerTicketMessage): TicketMutationResult { const ticket = this.findTicket(id); if (!ticket || !allowed(ticket)) return { ok: false, error: 'forbidden' }; if (ticket.status === 'بسته شده') return { ok: false, error: 'closed' }; if (!text.trim()) return { ok: false, error: 'empty' }; if (this.validateAttachments(files)) return { ok: false, error: 'invalid-attachments' }; if (!this.claim(key)) return { ok: false, error: 'duplicate' }; const timestamp = this.now(); this.state.update(items => items.map(item => item.id === id ? { ...status(item), updatedAt: timestamp, messages: [...item.messages, { ...build(item), sentAt: timestamp }] } : item)); return { ok: true }; }
  private mutate(id: number, allowed: (ticket: EmployerTicketRecord) => boolean, change: (ticket: EmployerTicketRecord) => EmployerTicketRecord): TicketMutationResult { const ticket = this.findTicket(id); if (!ticket || !allowed(ticket)) return { ok: false, error: 'forbidden' }; this.state.update(items => items.map(item => item.id === id ? change(item) : item)); return { ok: true }; }
  private message(authorName: string, authorRole: string, senderSide: Fish24TicketActorSide, text: string, files: readonly File[], sentAt = this.now()): EmployerTicketMessage { return { id: this.nextMessageId++, authorName, authorRole, senderDisplay: authorName, senderSide, sentAt, text, attachments: files.map(file => ({ id: this.nextAttachmentId++, name: file.name, size: file.size, type: file.type, blob: file.slice(0, file.size, file.type) })) }; }
  private claim(key: string): boolean { if (!key.trim() || this.handledSubmissions.has(key)) return false; this.handledSubmissions.add(key); return true; }
  private validDepartment(value: string): value is Fish24TicketDepartment { return FISH24_TICKET_DEPARTMENTS.some(item => item.id === value); }
  private employerProjection(ticket: EmployerTicketRecord): EmployerTicketPublicRecord { const { referrals, ...projection } = ticket; void referrals; return projection; }
  private isInternal(role: Fish24RoleId): boolean { return INTERNAL_ROLES.includes(role); }
  private internalRoleLabel(role: Fish24RoleId): string { return role === 'super-admin' ? 'مدیریت' : role === 'sales-expert' ? 'فروش' : 'پشتیبانی'; }
  private now(): string { const parts = new Intl.DateTimeFormat('fa-IR-u-ca-persian-nu-latn', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }).formatToParts(new Date()); const value = (type: Intl.DateTimeFormatPartTypes) => parts.find(part => part.type === type)?.value ?? ''; return `${value('year')}/${value('month')}/${value('day')} ${value('hour')}:${value('minute')}`; }
}
