import { Component, ViewEncapsulation, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { Fish24NewsCommentPreviewService } from '../../../../core/fish24/news/fish24-news-comment-preview.service';
import { Fish24NewsPreviewService } from '../../../../core/fish24/news/fish24-news-preview.service';

@Component({
  selector:'app-internal-news-preview',standalone:true,imports:[RouterLink],encapsulation:ViewEncapsulation.None,
  template:`<div class="fish24-news-preview mx-auto max-w-5xl space-y-5 animate-fade-in-up" dir="rtl">@if(item;as news){<header class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-sm text-muted">پیش‌نمایش داخلی؛ بازدید عمومی ثبت نمی‌شود</p><h1 class="mt-1 text-2xl font-black text-primary sm:text-3xl">{{news.title}}</h1></div><div class="flex gap-2"><a class="secondary" routerLink="/fish24/internal/news">بازگشت</a><a class="primary" [routerLink]="['/fish24/internal/news',news.id,'edit']">ویرایش</a></div></header><article class="card overflow-hidden">@if(news.mainImageUrl){<img [src]="news.mainImageUrl" [alt]="news.imageAlt||news.title" [title]="news.imageTitle" class="max-h-[28rem] w-full bg-background object-contain">}<div class="space-y-5 p-4 sm:p-7"><div class="flex flex-wrap items-center gap-2"><span [class]="news.active?'badge bg-success/15 text-success':'badge bg-muted/15 text-muted'">{{news.active?'فعال':'غیرفعال'}}</span><span class="text-xs text-muted">{{news.createdAt}}</span>@for(categoryId of news.categoryIds;track categoryId){@if(service.category(categoryId);as category){<span class="badge bg-primary/10 text-primary">{{category.name}}{{category.active?'':' (غیرفعال)'}}</span>}}</div><p class="rounded-xl bg-background p-4 font-bold leading-8">{{news.shortDescription}}</p><div class="rich-content" [innerHTML]="news.contentHtml"></div><dl class="grid gap-3 border-t border-border pt-5 text-sm sm:grid-cols-3"><div><dt>کامنت‌ها</dt><dd>{{service.approvedCommentCount(news.id)}}</dd></div><div><dt>لایک‌ها</dt><dd>{{news.likeCount}}</dd></div><div><dt>بازدیدهای Fixture نمایشی</dt><dd>{{news.viewCount}}</dd></div></dl></div></article><section class="card p-4 sm:p-6"><div class="mb-4 flex items-center justify-between gap-3"><h2 class="text-xl font-black">دیدگاه‌های تأییدشده</h2><a class="secondary" routerLink="/fish24/internal/news/comments">مدیریت دیدگاه‌ها</a></div><div class="space-y-3">@for(comment of comments.approvedForNews(news.id);track comment.id){<article class="rounded-xl border border-border p-4 dark:border-slate-700"><div class="flex flex-wrap items-center justify-between gap-2"><strong>{{comment.authorName}}</strong><span class="text-xs text-muted">{{comment.createdAt}}</span></div><p class="literal-text mt-3">{{comment.message}}</p>@if(comment.response){<div class="mt-3 rounded-xl bg-primary/5 p-3"><p class="text-xs font-black text-primary">پاسخ {{comment.responseAuthor}}</p><p class="literal-text mt-2">{{comment.response}}</p></div>}</article>}@empty{<p class="py-5 text-center text-muted">دیدگاه تأییدشده‌ای برای نمایش وجود ندارد.</p>}</div></section>}@else{<section class="card p-8 text-center"><p class="font-bold">خبر یافت نشد.</p><a class="secondary mt-4" routerLink="/fish24/internal/news">بازگشت به لیست</a></section>}</div>`,
  styles:[`.fish24-news-preview .card{border:1px solid rgb(var(--color-border));border-radius:1rem;background:rgb(var(--color-surface));box-shadow:0 1px 3px rgb(15 23 42/.08)}.fish24-news-preview .primary,.fish24-news-preview .secondary{display:inline-flex;min-height:2.6rem;align-items:center;justify-content:center;border-radius:.75rem;padding-inline:1rem;font-size:.8rem;font-weight:800}.fish24-news-preview .primary{background:rgb(var(--color-primary));color:#fff}.fish24-news-preview .secondary{border:1px solid rgb(var(--color-border))}.fish24-news-preview .badge{display:inline-flex;border-radius:999px;padding:.3rem .7rem;font-size:.7rem;font-weight:800}.fish24-news-preview .rich-content{line-height:2;overflow-wrap:anywhere}.fish24-news-preview .rich-content :where(h1,h2,h3){font-weight:900;margin-block:1rem .4rem}.fish24-news-preview .rich-content h1{font-size:1.7rem}.fish24-news-preview .rich-content h2{font-size:1.4rem}.fish24-news-preview .rich-content h3{font-size:1.15rem}.fish24-news-preview .rich-content :where(ul,ol){padding-inline-start:1.5rem}.fish24-news-preview .rich-content ul{list-style:disc}.fish24-news-preview .rich-content ol{list-style:decimal}.fish24-news-preview .rich-content blockquote{border-inline-start:4px solid rgb(var(--color-primary));background:rgb(var(--color-primary)/.06);padding:.6rem 1rem;border-radius:.5rem}.fish24-news-preview .rich-content a{color:rgb(var(--color-primary));text-decoration:underline}.fish24-news-preview .rich-content img{max-width:100%;height:auto;border-radius:.75rem}.fish24-news-preview .rich-content table{display:block;max-width:100%;overflow-x:auto;border-collapse:collapse}.fish24-news-preview .rich-content :where(th,td){border:1px solid rgb(var(--color-border));padding:.5rem;min-width:5rem}.fish24-news-preview dt{color:rgb(var(--color-muted));font-size:.72rem}.fish24-news-preview dd{margin-top:.25rem;font-weight:900}.fish24-news-preview .literal-text{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.9}`]
})
export class InternalNewsPreviewComponent{readonly service=inject(Fish24NewsPreviewService);readonly comments=inject(Fish24NewsCommentPreviewService);private readonly route=inject(ActivatedRoute);readonly item=this.service.newsItem(Number(this.route.snapshot.paramMap.get('id')));}
