import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { CategoryDraft, Fish24NewsCategory, Fish24NewsItem, Fish24NewsPreviewService } from '../../../../core/fish24/news/fish24-news-preview.service';
import { Fish24RolePreviewService } from '../../../../core/fish24/dev/fish24-role-preview.service';
import { InternalListColumn, InternalListColumnSearches, InternalListSort, filterByInternalListColumns, nextInternalListSort, sortInternalListRows } from '../../../../shared/ui/data-list/internal-list.model';
import { InternalListPreferencesService } from '../../../../shared/ui/data-list/internal-list-preferences.service';
import { PlainXlsxService } from '../../../../shared/ui/data-list/plain-xlsx.service';
import { IconComponent } from '../../../../shared/ui/icon/icon.component';
import { ToastService } from '../../../../shared/ui/toast/toast.service';
import { NewsImagePickerComponent } from '../../../../shared/fish24/news/news-image-picker.component';

interface NewsFilters { readonly categoryId: string; readonly title: string; }
interface CategoryFilters { readonly name: string; }
const NEWS_DEFAULTS: NewsFilters = { categoryId: 'all', title: '' };
const CATEGORY_DEFAULTS: CategoryFilters = { name: '' };

@Component({
  selector: 'app-internal-news-management',
  standalone: true,
  imports: [FormsModule, RouterLink, IconComponent, NewsImagePickerComponent],
  template: `
    <div class="mx-auto max-w-[96%] space-y-4 animate-fade-in-up sm:space-y-5" dir="rtl">
      <header class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div class="flex items-center gap-3"><span class="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10"><ui-icon name="newspaper" [size]="26" class="text-primary"></ui-icon></span><div><h1 class="text-2xl font-black text-primary sm:text-3xl">{{ categoriesMode ? 'دسته‌بندی اخبار' : 'مدیریت اخبار' }}</h1><p class="text-sm text-muted">پیش‌نمایش داخلی محتوای خبری Fish24</p></div></div>
        @if (categoriesMode) { <button type="button" class="primary" (click)="openCategory()"><ui-icon name="plus" [size]="17"></ui-icon>دسته‌بندی جدید</button> }
        @else { <a routerLink="/fish24/internal/news/new" class="primary"><ui-icon name="plus" [size]="17"></ui-icon>خبر جدید</a> }
      </header>

      <nav class="flex flex-wrap gap-2" aria-label="بخش‌های مدیریت اخبار">
        <a routerLink="/fish24/internal/news" class="tab" [class.active]="!categoriesMode">لیست اخبار</a>
        <a routerLink="/fish24/internal/news/categories" class="tab" [class.active]="categoriesMode">دسته‌بندی اخبار</a>
      </nav>

      <section class="card p-4 sm:p-5">
        <div class="mb-3 flex items-center gap-2"><ui-icon name="search" [size]="18" class="text-primary"></ui-icon><h2 class="text-lg font-extrabold">جستجو</h2></div>
        @if (categoriesMode) {
          <form class="grid items-end gap-3 sm:grid-cols-[minmax(0,1fr)_auto]" (submit)="applyCategoryFilters($event)"><label class="label">نام دسته‌بندی<input [(ngModel)]="categoryDraftFilter.name" name="categoryName" class="input"></label><div class="flex gap-2"><button class="primary" type="submit">جستجو</button><button class="secondary" type="button" (click)="showAllCategories()">مشاهده همه</button></div></form>
        } @else {
          <form class="grid items-end gap-3 sm:grid-cols-2 xl:grid-cols-[15rem_minmax(0,1fr)_auto]" (submit)="applyNewsFilters($event)"><label class="label">دسته‌بندی<select [(ngModel)]="newsDraftFilter.categoryId" name="category" class="input"><option value="all">همه دسته‌بندی‌ها</option>@for (category of service.categories(); track category.id) {<option [value]="category.id">{{ category.name }}{{ category.active ? '' : ' (غیرفعال)' }}</option>}</select></label><label class="label">عنوان خبر<input [(ngModel)]="newsDraftFilter.title" name="title" class="input"></label><div class="flex gap-2"><button class="primary" type="submit">جستجو</button><button class="secondary" type="button" (click)="showAllNews()">مشاهده همه</button></div></form>
        }
      </section>

      <section class="card overflow-hidden">
        <div class="flex flex-col gap-3 border-b border-border p-4 dark:border-slate-700 sm:flex-row sm:items-center sm:justify-between">
          <h2 class="text-lg font-extrabold">{{ categoriesMode ? 'لیست دسته‌بندی اخبار' : 'لیست اخبار' }} ({{ number(filteredCount()) }} رکورد)</h2>
          <div class="flex flex-wrap gap-2"><button type="button" class="toolbar" (click)="columnChooserOpen.set(!columnChooserOpen())"><ui-icon name="sliders" [size]="16"></ui-icon>انتخاب ستون</button>@if (canExport()) {<button type="button" class="toolbar text-success" (click)="exportRows()"><ui-icon name="download" [size]="16"></ui-icon>Excel</button>}</div>
        </div>
        @if (columnChooserOpen()) {<div class="border-b border-border bg-background/60 p-3 dark:border-slate-700"><div class="flex flex-wrap gap-2">@for (column of columns(); track column.id) {<label class="choice"><input type="checkbox" class="accent-primary" [checked]="visible(column.id)" [disabled]="onlyVisible(column.id)" (change)="toggleColumn(column.id,$event)">{{ column.label }}</label>}<button type="button" class="px-3 py-2 text-xs font-bold text-primary" (click)="restoreColumns()">بازگردانی ستون‌های پیش‌فرض</button></div></div>}
        <div class="max-w-full overflow-x-auto">
          <table class="w-full min-w-max text-sm"><thead class="bg-background/80 dark:bg-slate-900/60"><tr>@for (column of visibleColumns(); track column.id) {<th class="px-3 py-3 text-right text-xs font-bold text-muted" [style.min-width]="column.minWidth"><button type="button" class="flex w-full items-center justify-between gap-2" (click)="sort(column.id)"><span>{{ column.label }}</span><span>{{ sortMark(column.id) }}</span></button></th>}<th class="min-w-48 px-3 py-3 text-right text-xs font-bold text-muted">عملیات</th></tr><tr>@for (column of visibleColumns(); track column.id) {<th class="px-2 pb-2"><input type="search" class="header-search" [value]="columnSearches()[column.id] || ''" [attr.aria-label]="'جستجو در ' + column.label" (input)="searchColumn(column.id,value($event))"></th>}<th></th></tr></thead>
            <tbody class="divide-y divide-border dark:divide-slate-700">
              @if (categoriesMode) {@for (row of categoryPageRows(); track row.id) {<tr class="hover:bg-primary/5">@for (column of visibleColumns(); track column.id) {<td class="px-3 py-3 align-middle">@switch(column.id){@case('image'){@if(row.imageUrl){<img [src]="row.imageUrl" [alt]="row.imageAlt || row.name" class="h-12 w-16 rounded-lg object-cover">}@else{<span class="text-muted">—</span>}}@case('name'){<a class="font-bold text-primary hover:underline" [routerLink]="['/fish24/internal/news']" [queryParams]="{category:row.id}">{{row.name}}</a>}@case('status'){<span [class]="statusClass(row.active)">{{row.active?'فعال':'غیرفعال'}}</span>}@default{<span [attr.dir]="column.ltr?'ltr':null">{{cellValue(column,row)}}</span>}}</td>}<td class="px-3 py-3"><div class="flex flex-wrap gap-2"><button class="action" type="button" (click)="openCategory(row)">ویرایش</button><button class="action" type="button" (click)="toggleCategory(row)">{{row.active?'غیرفعال‌سازی':'فعال‌سازی'}}</button><button class="danger" type="button" (click)="deleteCategory(row)">حذف</button></div></td></tr>}@empty{<tr><td [attr.colspan]="visibleColumns().length+1" class="p-8 text-center text-muted">دسته‌بندی‌ای یافت نشد.</td></tr>}}
              @else {@for (row of newsPageRows(); track row.id) {<tr class="hover:bg-primary/5">@for (column of visibleColumns(); track column.id) {<td class="px-3 py-3 align-middle">@switch(column.id){@case('image'){@if(row.mainImageUrl){<img [src]="row.mainImageUrl" [alt]="row.imageAlt || row.title" class="h-12 w-16 rounded-lg object-cover">}@else{<span class="text-muted">—</span>}}@case('title'){<a class="max-w-sm font-bold text-primary hover:underline" [routerLink]="['/fish24/internal/news',row.id]">{{row.title}}</a>}@case('categories'){<div class="flex max-w-sm flex-wrap gap-1">@for(name of service.categoryNames(row.categoryIds);track name){<span class="rounded-full bg-primary/10 px-2 py-1 text-xs font-bold text-primary">{{name}}</span>}</div>}@case('status'){<span [class]="statusClass(row.active)">{{row.active?'فعال':'غیرفعال'}}</span>}@default{<span [attr.dir]="column.ltr?'ltr':null">{{cellValue(column,row)}}</span>}}</td>}<td class="px-3 py-3"><div class="flex flex-wrap gap-2"><a class="action" [routerLink]="['/fish24/internal/news',row.id]">پیش‌نمایش</a><a class="action" [routerLink]="['/fish24/internal/news',row.id,'edit']">ویرایش</a><button class="action" type="button" (click)="toggleNews(row)">{{row.active?'غیرفعال‌سازی':'فعال‌سازی'}}</button><button class="danger" type="button" (click)="deleteNews(row)">حذف</button></div></td></tr>}@empty{<tr><td [attr.colspan]="visibleColumns().length+1" class="p-8 text-center text-muted">خبری یافت نشد.</td></tr>}}
            </tbody></table>
        </div>
        <div class="flex items-center justify-between border-t border-border p-3 dark:border-slate-700"><span class="text-xs text-muted">صفحه {{number(page())}} از {{number(totalPages())}}</span><div class="flex gap-2"><button class="secondary" type="button" [disabled]="page()===1" (click)="page.set(page()-1)">قبلی</button><button class="secondary" type="button" [disabled]="page()===totalPages()" (click)="page.set(page()+1)">بعدی</button></div></div>
      </section>
    </div>

    @if (categoryModal()) {<div class="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/55 p-3" dir="rtl" role="dialog" aria-modal="true" aria-labelledby="category-form-title"><form class="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-surface p-4 shadow-2xl dark:bg-slate-800 sm:p-6" (submit)="saveCategory($event)"><div class="flex items-center justify-between"><h2 id="category-form-title" class="text-xl font-black">{{editingCategoryId?'ویرایش دسته‌بندی':'ایجاد دسته‌بندی جدید'}}</h2><button type="button" class="icon-button" aria-label="بستن" (click)="categoryModal.set(false)">×</button></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="label">نام دسته‌بندی *<input class="input" name="name" [(ngModel)]="categoryForm.name" (input)="categoryNameChanged()"></label><label class="label">اسلاگ *<input class="input" name="slug" dir="ltr" [(ngModel)]="categoryForm.slug" (input)="categorySlugManual=true"></label><label class="label sm:col-span-2">توضیحات کوتاه<textarea class="input min-h-24 py-2" name="description" [(ngModel)]="categoryForm.shortDescription"></textarea></label><label class="label">ترتیب<input class="input" name="order" type="number" min="0" step="1" [(ngModel)]="categoryForm.order"></label><label class="label">وضعیت<select class="input" name="active" [(ngModel)]="categoryForm.active"><option [ngValue]="true">فعال</option><option [ngValue]="false">غیرفعال</option></select></label><div class="sm:col-span-2"><span class="label">تصویر</span><app-news-image-picker inputId="category-image" [value]="categoryForm.imageUrl" [alt]="categoryForm.imageAlt" (valueChange)="categoryForm.imageUrl=$event"></app-news-image-picker></div><label class="label">Alt تصویر<input class="input" name="alt" [(ngModel)]="categoryForm.imageAlt"></label><label class="label">Title تصویر<input class="input" name="imageTitle" [(ngModel)]="categoryForm.imageTitle"></label><label class="label sm:col-span-2">کلمات کلیدی<input class="input" name="keywords" [(ngModel)]="categoryForm.keywords"></label><label class="label sm:col-span-2">توضیحات متا<textarea class="input min-h-20 py-2" name="meta" [(ngModel)]="categoryForm.metaDescription"></textarea></label></div>@if(categoryError()){<p role="alert" class="mt-4 rounded-xl bg-danger/10 p-3 text-sm font-bold text-danger">{{categoryError()}}</p>}<div class="mt-5 flex justify-end gap-2"><button type="button" class="secondary" (click)="categoryModal.set(false)">انصراف</button><button type="submit" class="primary">ذخیره دسته‌بندی</button></div></form></div>}
  `,
  styles: [`
    .card{border:1px solid rgb(var(--color-border));border-radius:1rem;background:rgb(var(--color-surface));box-shadow:0 1px 3px rgb(15 23 42/.08)}.label{display:block;font-size:.78rem;font-weight:800;color:rgb(var(--color-foreground))}.input{display:block;width:100%;min-height:2.7rem;margin-top:.35rem;border:1px solid rgb(var(--color-border));border-radius:.75rem;background:rgb(var(--color-background));padding-inline:.75rem;outline:none}.input:focus,.header-search:focus{border-color:rgb(var(--color-primary));box-shadow:0 0 0 2px rgb(var(--color-primary)/.15)}.primary,.secondary,.toolbar,.tab,.action,.danger,.icon-button{display:inline-flex;align-items:center;justify-content:center;gap:.4rem;border-radius:.7rem;font-size:.78rem;font-weight:800;transition:.15s}.primary{min-height:2.65rem;background:rgb(var(--color-primary));color:#fff;padding-inline:1rem}.secondary,.toolbar,.tab,.action{min-height:2.4rem;border:1px solid rgb(var(--color-border));padding-inline:.75rem}.tab.active{border-color:rgb(var(--color-primary));background:rgb(var(--color-primary)/.1);color:rgb(var(--color-primary))}.danger{min-height:2.4rem;border:1px solid rgb(var(--color-danger)/.25);padding-inline:.7rem;color:rgb(var(--color-danger))}.icon-button{height:2.4rem;width:2.4rem;font-size:1.5rem}.choice{display:flex;align-items:center;gap:.4rem;border:1px solid rgb(var(--color-border));border-radius:.65rem;padding:.5rem .7rem;font-size:.72rem;font-weight:700}.header-search{height:2.15rem;width:100%;border:1px solid rgb(var(--color-border));border-radius:.55rem;background:rgb(var(--color-surface));padding-inline:.5rem;font-size:.72rem;outline:none}button:disabled{opacity:.45;cursor:not-allowed}
  `]
})
export class InternalNewsManagementComponent {
  readonly service = inject(Fish24NewsPreviewService);
  private readonly roles = inject(Fish24RolePreviewService); private readonly prefs = inject(InternalListPreferencesService); private readonly xlsx = inject(PlainXlsxService); private readonly toast = inject(ToastService); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router);
  readonly categoriesMode = this.router.url.includes('/categories');
  readonly page = signal(1); readonly pageSize = 10; readonly columnChooserOpen = signal(false); readonly categoryModal = signal(false); readonly categoryError = signal('');
  editingCategoryId: number | null = null; categorySlugManual = false;
  categoryForm: CategoryDraft = this.emptyCategory();
  categoryDraftFilter = { ...CATEGORY_DEFAULTS }; newsDraftFilter = { ...NEWS_DEFAULTS };
  readonly appliedCategoryFilters = signal(this.prefs.loadFilters<CategoryFilters>('internal-news-categories', CATEGORY_DEFAULTS, value => typeof value === 'object' && value !== null && typeof (value as CategoryFilters).name === 'string' ? { name: (value as CategoryFilters).name } : null));
  readonly appliedNewsFilters = signal(this.initialNewsFilters());
  readonly columnSearches = signal<InternalListColumnSearches>({}); readonly tableSort = signal<InternalListSort>({ columnId: null, direction: null });

  readonly categoryColumns: readonly InternalListColumn<Fish24NewsCategory>[] = [
    {id:'id',label:'شناسه',value:r=>r.id,exportValue:r=>r.id,minWidth:'6rem',ltr:true},{id:'image',label:'تصویر',value:r=>r.imageUrl,exportValue:r=>r.imageUrl,minWidth:'7rem'},{id:'name',label:'عنوان دسته‌بندی',value:r=>r.name,minWidth:'15rem'},{id:'count',label:'تعداد اخبار',value:r=>this.service.categoryNewsCount(r.id),exportValue:r=>this.service.categoryNewsCount(r.id),minWidth:'8rem'},{id:'status',label:'وضعیت',value:r=>r.active?'فعال':'غیرفعال',minWidth:'8rem'}
  ];
  readonly newsColumns: readonly InternalListColumn<Fish24NewsItem>[] = [
    {id:'id',label:'شناسه',value:r=>r.id,exportValue:r=>r.id,minWidth:'6rem',ltr:true},{id:'createdAt',label:'تاریخ ایجاد',value:r=>r.createdAt,minWidth:'9rem',ltr:true},{id:'image',label:'تصویر خبر',value:r=>r.mainImageUrl,exportValue:r=>r.mainImageUrl,minWidth:'7rem'},{id:'title',label:'عنوان خبر',value:r=>r.title,minWidth:'20rem'},{id:'categories',label:'دسته‌بندی',value:r=>this.service.categoryNames(r.categoryIds).join('، '),searchValue:r=>this.service.categoryNames(r.categoryIds).join(' '),exportValue:r=>this.service.categoryNames(r.categoryIds).join('، '),minWidth:'16rem'},{id:'comments',label:'کامنت‌ها',value:r=>r.commentCount,exportValue:r=>r.commentCount,minWidth:'7rem'},{id:'likes',label:'لایک‌ها',value:r=>r.likeCount,exportValue:r=>r.likeCount,minWidth:'7rem'},{id:'views',label:'بازدیدها',value:r=>r.viewCount,exportValue:r=>r.viewCount,minWidth:'7rem'},{id:'status',label:'وضعیت',value:r=>r.active?'فعال':'غیرفعال',minWidth:'8rem'}
  ];
  readonly allColumnIds = (this.categoriesMode ? this.categoryColumns : this.newsColumns).map(column=>column.id); readonly defaultColumnIds = [...this.allColumnIds];
  readonly selectedColumns = signal<readonly string[]>(this.prefs.load(this.listId(),this.allColumnIds,this.defaultColumnIds));
  readonly columns = computed(() => this.categoriesMode ? this.categoryColumns : this.newsColumns);
  readonly visibleColumns = computed(() => this.columns().filter(column=>this.selectedColumns().includes(column.id)));
  readonly filteredCategories = computed(() => this.service.categories().filter(row=>!this.appliedCategoryFilters().name || row.name.includes(this.appliedCategoryFilters().name.trim())));
  readonly filteredNews = computed(() => {const f=this.appliedNewsFilters();return this.service.news().filter(row=>(f.categoryId==='all'||row.categoryIds.includes(Number(f.categoryId)))&&(!f.title||row.title.includes(f.title.trim())));});
  readonly categoryTableRows = computed(() => sortInternalListRows(filterByInternalListColumns(this.filteredCategories(),this.categoryColumns,this.selectedColumns(),this.columnSearches()),this.categoryColumns,this.tableSort()));
  readonly newsTableRows = computed(() => sortInternalListRows(filterByInternalListColumns(this.filteredNews(),this.newsColumns,this.selectedColumns(),this.columnSearches()),this.newsColumns,this.tableSort()));
  readonly categoryPageRows = computed(() => this.categoryTableRows().slice((this.page()-1)*this.pageSize,this.page()*this.pageSize)); readonly newsPageRows = computed(() => this.newsTableRows().slice((this.page()-1)*this.pageSize,this.page()*this.pageSize));
  readonly filteredCount = computed(()=>this.categoriesMode?this.filteredCategories().length:this.filteredNews().length); readonly totalPages=computed(()=>Math.max(1,Math.ceil((this.categoriesMode?this.categoryTableRows().length:this.newsTableRows().length)/this.pageSize)));

  constructor(){this.categoryDraftFilter={...this.appliedCategoryFilters()};this.newsDraftFilter={...this.appliedNewsFilters()};}
  canExport(){return this.service.canExport(this.roles.getPreviewRole());} visible(id:string){return this.selectedColumns().includes(id);} onlyVisible(id:string){return this.visible(id)&&this.selectedColumns().length===1;} value(e:Event){return(e.target as HTMLInputElement).value;} number(v:number){return new Intl.NumberFormat('fa-IR').format(v);} statusClass(active:boolean){return`inline-flex rounded-full px-3 py-1 text-xs font-bold ${active?'bg-success/15 text-success':'bg-muted/15 text-muted'}`;}
  cellValue(column:InternalListColumn<Fish24NewsCategory>|InternalListColumn<Fish24NewsItem>,row:Fish24NewsCategory|Fish24NewsItem){return (column as InternalListColumn<any>).value(row);}
  applyCategoryFilters(e:Event){e.preventDefault();const f={name:this.categoryDraftFilter.name.trim()};this.appliedCategoryFilters.set(f);this.prefs.saveFilters(this.listId(),f);this.page.set(1);} showAllCategories(){this.categoryDraftFilter={...CATEGORY_DEFAULTS};this.appliedCategoryFilters.set(CATEGORY_DEFAULTS);this.prefs.resetFilters(this.listId());this.page.set(1);}
  applyNewsFilters(e:Event){e.preventDefault();const categoryId=this.service.category(Number(this.newsDraftFilter.categoryId))?String(this.newsDraftFilter.categoryId):'all';const f={categoryId,title:this.newsDraftFilter.title.trim()};this.appliedNewsFilters.set(f);this.prefs.saveFilters(this.listId(),f);this.page.set(1);} showAllNews(){this.newsDraftFilter={...NEWS_DEFAULTS};this.appliedNewsFilters.set(NEWS_DEFAULTS);this.prefs.resetFilters(this.listId());this.page.set(1);void this.router.navigate([], {relativeTo:this.route,queryParams:{},replaceUrl:true});}
  toggleColumn(id:string,e:Event){const checked=(e.target as HTMLInputElement).checked;const next=checked?[...this.selectedColumns(),id]:this.selectedColumns().filter(x=>x!==id);if(!next.length)return;this.selectedColumns.set(this.prefs.save(this.listId(),next,this.allColumnIds));if(!checked)this.searchColumn(id,'');} restoreColumns(){this.selectedColumns.set(this.prefs.reset(this.listId(),this.allColumnIds,this.defaultColumnIds));this.columnSearches.set({});this.tableSort.set({columnId:null,direction:null});} searchColumn(id:string,value:string){this.columnSearches.update(v=>({...v,[id]:value}));this.page.set(1);} sort(id:string){this.tableSort.update(v=>nextInternalListSort(v,id));} sortMark(id:string){const s=this.tableSort();return s.columnId===id?(s.direction==='asc'?'↑':'↓'):'↕';}
  exportRows(){if(!this.canExport()){this.toast.show('نقش پشتیبانی مجوز خروجی Excel ندارد.','error');return;}const cols=this.visibleColumns();const source=this.categoriesMode?this.filteredCategories():this.filteredNews();const rows=source.map((row:any)=>cols.map((column:any)=>column.exportValue?column.exportValue(row):column.value(row)==null?null:String(column.value(row))));this.xlsx.export(this.categoriesMode?'fish24-news-categories.xlsx':'fish24-news.xlsx',cols.map(c=>c.label),rows);this.toast.show(`${this.number(rows.length)} رکورد برای Excel آماده شد.`,'success');}
  openCategory(row?:Fish24NewsCategory){this.editingCategoryId=row?.id??null;this.categorySlugManual=Boolean(row);this.categoryError.set('');this.categoryForm=row?{name:row.name,slug:row.slug,shortDescription:row.shortDescription,order:row.order,imageUrl:row.imageUrl,imageAlt:row.imageAlt,imageTitle:row.imageTitle,keywords:row.keywords,metaDescription:row.metaDescription,active:row.active}:this.emptyCategory();this.categoryModal.set(true);} categoryNameChanged(){if(!this.categorySlugManual)this.categoryForm.slug=this.service.normalizeSlug(this.categoryForm.name);} saveCategory(e:Event){e.preventDefault();const result=this.editingCategoryId?this.service.updateCategory(this.roles.getPreviewRole(),this.editingCategoryId,this.categoryForm):this.service.createCategory(this.roles.getPreviewRole(),this.categoryForm);if(!result.ok){this.categoryError.set(result.error);return;}this.categoryModal.set(false);this.toast.show('دسته‌بندی ذخیره شد.','success');}
  toggleCategory(row:Fish24NewsCategory){const r=this.service.toggleCategory(this.roles.getPreviewRole(),row.id);this.toast.show(r.ok?'وضعیت دسته‌بندی تغییر کرد.':r.error,r.ok?'success':'error');} deleteCategory(row:Fish24NewsCategory){if(!confirm(`حذف دسته‌بندی «${row.name}»؟`))return;const r=this.service.deleteCategory(this.roles.getPreviewRole(),row.id);this.toast.show(r.ok?'دسته‌بندی حذف شد.':r.error,r.ok?'success':'error');}
  toggleNews(row:Fish24NewsItem){const r=this.service.toggleNews(this.roles.getPreviewRole(),row.id);this.toast.show(r.ok?'وضعیت خبر تغییر کرد.':r.error,r.ok?'success':'error');} deleteNews(row:Fish24NewsItem){if(!confirm(`حذف خبر «${row.title}»؟`))return;const r=this.service.deleteNews(this.roles.getPreviewRole(),row.id);this.toast.show(r.ok?'خبر و روابط دسته‌بندی آن حذف شد.':r.error,r.ok?'success':'error');}
  private listId(){return this.categoriesMode?'internal-news-categories':'internal-news-items';} private emptyCategory():CategoryDraft{return{name:'',slug:'',shortDescription:'',order:0,imageUrl:'',imageAlt:'',imageTitle:'',keywords:'',metaDescription:'',active:true};}
  private initialNewsFilters():NewsFilters{const stored=this.prefs.loadFilters<NewsFilters>('internal-news-items',NEWS_DEFAULTS,value=>{if(typeof value!=='object'||value===null)return null;const item=value as Partial<NewsFilters>;return{categoryId:typeof item.categoryId==='string'&&(item.categoryId==='all'||Boolean(this.service.category(Number(item.categoryId))))?item.categoryId:'all',title:typeof item.title==='string'?item.title:''};});const query=this.route.snapshot.queryParamMap.get('category');if(query&&this.service.category(Number(query))){const filters={...stored,categoryId:query};this.prefs.saveFilters('internal-news-items',filters);return filters;}return stored;}
}
