import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthService } from '../../../../core/auth/auth.service';
import { EmployerTicketMessage, Fish24TicketAttachment, Fish24TicketPreviewService } from '../../../../core/fish24/tickets/fish24-ticket-preview.service';
import { IconComponent } from '../../../../shared/ui/icon/icon.component';
import { ToastService } from '../../../../shared/ui/toast/toast.service';
import { TicketAttachmentPickerComponent } from '../../../../shared/fish24/tickets/ticket-attachment-picker.component';

@Component({ selector: 'app-employer-ticket-view', standalone: true, imports: [FormsModule, RouterLink, IconComponent, TicketAttachmentPickerComponent], template: `
@if (ticket(); as t) {<div class="mx-auto max-w-6xl space-y-4" dir="rtl">
  <header class="card flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex items-center gap-2"><h1 class="text-xl font-extrabold sm:text-2xl">{{ t.subject }}</h1><span [class]="statusClass(t.status)">{{ t.status }}</span></div><p class="mt-1 text-sm text-muted">تیکت #{{ t.id }} · ایجاد {{ t.createdAt }} · بروزرسانی {{ t.updatedAt }}</p></div><div class="flex flex-wrap gap-2"><a routerLink="/fish24/employer/tickets" class="secondary">بازگشت به فهرست</a><button type="button" (click)="toggleClosed()" [class]="t.status === 'بسته شده' ? 'primary' : 'danger'">{{ t.status === 'بسته شده' ? 'بازگشایی تیکت' : 'بستن تیکت' }}</button></div></header>
  <div class="grid gap-4 lg:grid-cols-[minmax(0,1fr)_18rem]">
    <main class="space-y-4"><section class="card p-4 sm:p-5"><h2 class="mb-4 text-lg font-extrabold">گفت‌وگو</h2><ol class="space-y-3">@for (message of t.messages; track message.id) {<li [class]="message.senderSide === 'employer' ? 'flex justify-start' : 'flex justify-end'"><article [class]="message.senderSide === 'employer' ? 'message employer' : 'message internal'"><div class="flex flex-wrap items-center justify-between gap-2"><div><strong>{{ message.authorName }}</strong><span class="mr-2 text-xs text-muted">{{ message.authorRole }}</span></div><time class="text-xs text-muted" dir="ltr">{{ message.sentAt }}</time></div><p class="mt-3 whitespace-pre-wrap break-words leading-7">{{ message.text }}</p>@if (message.attachments.length) {<div class="mt-3 grid gap-2 sm:grid-cols-2">@for (file of message.attachments; track file.id) {<button type="button" (click)="download(message, file)" class="attachment"><ui-icon [name]="file.type.startsWith('image/') ? 'image' : 'paperclip'" [size]="18"></ui-icon><span class="min-w-0 flex-1 truncate text-right">{{ file.name }}</span><small>{{ size(file.size) }}</small></button>}</div>}</article></li>}</ol></section>
    @if (t.status !== 'بسته شده') {<section class="card p-4 sm:p-5"><h2 class="text-lg font-extrabold">ثبت پاسخ</h2><form class="mt-3 space-y-3" (submit)="submit($event)"><textarea [(ngModel)]="replyText" name="reply" rows="5" class="input h-auto py-3" placeholder="متن پاسخ را بنویسید..."></textarea><app-ticket-attachment-picker inputId="employer-reply-files" [files]="files()" [errorMessage]="error()" (filesSelected)="selectFiles($event)" (removeFile)="remove($event)"></app-ticket-attachment-picker><button type="submit" class="primary" [disabled]="submitting()">ارسال پاسخ</button></form></section>} @else {<section class="card p-5 text-center"><ui-icon name="lock" [size]="26" class="mx-auto text-muted"></ui-icon><p class="mt-2 font-bold">این تیکت بسته است و امکان ثبت پاسخ ندارد.</p><button type="button" (click)="toggleClosed()" class="primary mt-3">بازگشایی تیکت</button></section>}
    </main>
    <aside class="card h-fit p-4"><h2 class="text-lg font-extrabold">اطلاعات تیکت</h2><dl class="mt-3 space-y-3 text-sm"><div><dt>کارفرما</dt><dd>{{ t.employerName }}</dd></div><div><dt>شرکت / کارگاه</dt><dd>{{ t.companyName || '—' }}</dd></div><div><dt>موبایل</dt><dd dir="ltr">{{ t.employerMobile }}</dd></div><div><dt>دریافت‌کننده</dt><dd>{{ service.departmentLabel(t.recipientDepartment) }}</dd></div></dl></aside>
  </div>
</div>}
`, styles: [`.card{border:1px solid rgb(var(--color-border));border-radius:1rem;background:rgb(var(--color-surface));box-shadow:0 1px 3px rgb(15 23 42/.08)}.input{width:100%;min-height:2.75rem;border:1px solid rgb(var(--color-border));border-radius:.75rem;background:rgb(var(--color-background));padding-inline:.75rem}.primary,.secondary,.danger{display:inline-flex;min-height:2.65rem;align-items:center;justify-content:center;border-radius:.75rem;padding-inline:1rem;font-size:.85rem;font-weight:700}.primary{background:rgb(var(--color-primary));color:white}.danger{background:rgb(var(--color-danger));color:white}.secondary{border:1px solid rgb(var(--color-border))}.message{width:100%;max-width:46rem;border:1px solid rgb(var(--color-border));border-radius:1rem;padding:1rem}.employer{background:rgb(var(--color-background)/.65)}.internal{background:rgb(var(--color-primary)/.08);border-color:rgb(var(--color-primary)/.2)}.attachment{display:flex;align-items:center;gap:.5rem;border:1px solid rgb(var(--color-border));border-radius:.75rem;padding:.6rem}.file-chip{border:1px solid rgb(var(--color-border));border-radius:.6rem;padding:.35rem .6rem;font-size:.75rem}.file-chip button{color:rgb(var(--color-danger));margin-right:.4rem}dt{color:rgb(var(--color-muted));font-size:.75rem}dd{margin-top:.25rem;font-weight:700}`] })
export class EmployerTicketViewComponent {
  readonly service = inject(Fish24TicketPreviewService); private readonly auth = inject(AuthService); private readonly router = inject(Router); private readonly toast = inject(ToastService); private readonly id = Number(inject(ActivatedRoute).snapshot.paramMap.get('id'));
  private readonly ownerId = this.auth.currentUser()?.id ?? ''; readonly ticket = computed(() => this.service.findEmployerTicket(this.id, this.ownerId)); readonly files = signal<readonly File[]>([]); readonly error = signal(''); readonly submitting = signal(false); replyText = ''; private submissionKey = this.key();
  constructor(){ if(!this.service.findEmployerTicket(this.id,this.ownerId)) queueMicrotask(()=>void this.router.navigate(['/fish24/employer/tickets'])); }
  submit(event: Event): void { event.preventDefault(); if(this.submitting()) return; const validation=this.service.validateAttachments(this.files()); if(!this.replyText.trim()||validation){this.error.set(validation??'متن پاسخ الزامی است.');return;} this.submitting.set(true); const result=this.service.employerReply(this.id,this.ownerId,this.replyText,this.files(),this.submissionKey); this.submitting.set(false); if(!result.ok){this.error.set(result.error==='closed'?'تیکت بسته است.':'پاسخ ثبت نشد.');return;} this.replyText='';this.files.set([]);this.error.set('');this.submissionKey=this.key();this.toast.show('پاسخ در پیش‌نمایش ثبت شد.','success'); }
  toggleClosed(): void { const t=this.ticket(); if(!t)return; const result=t.status==='بسته شده'?this.service.reopenForEmployer(t.id,this.ownerId):this.service.closeForEmployer(t.id,this.ownerId); if(result.ok)this.toast.show(t.status==='بسته شده'?'تیکت بازگشایی شد.':'تیکت بسته شد.','success'); }
  selectFiles(selected:readonly File[]):void{const next=[...this.files(),...selected];const error=this.service.validateAttachments(next);this.error.set(error??'');if(!error)this.files.set(next);} remove(index:number):void{this.files.set(this.files().filter((_,i)=>i!==index));this.error.set('');}
  download(message:EmployerTicketMessage,file:Fish24TicketAttachment):void{const blob=this.service.attachmentBlob(this.id,message.id,file.id,{ownerId:this.ownerId});if(!blob)return;const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
  size(value:number):string{return value<1048576?`${Math.ceil(value/1024)} کیلوبایت`:`${(value/1048576).toFixed(1)} مگابایت`;} statusClass(status:string):string{return `inline-flex rounded-full px-3 py-1 text-xs font-bold ${status==='نیاز به بررسی'?'bg-warning/15 text-warning':status==='جواب داده شده'?'bg-success/15 text-success':'bg-muted/15 text-muted'}`;} private key():string{return `employer-reply-${Date.now()}-${Math.random()}`;}
}
