import {Component,computed,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute} from '@angular/router';
import {RouterLink} from '@angular/router';
import {Fish24GeographyService,GeographyCity,GeographyCounty,GeographyKind,GeographyProvince} from '../../../../core/fish24/geography/fish24-geography.service';
import {Fish24RolePreviewService} from '../../../../core/fish24/dev/fish24-role-preview.service';
import {InternalListColumn,InternalListColumnSearches,InternalListSort,filterByInternalListColumns,nextInternalListSort,sortInternalListRows} from '../../../../shared/ui/data-list/internal-list.model';
import {InternalListPreferencesService} from '../../../../shared/ui/data-list/internal-list-preferences.service';
import {PlainXlsxService} from '../../../../shared/ui/data-list/plain-xlsx.service';
import {IconComponent} from '../../../../shared/ui/icon/icon.component';
import {ToastService} from '../../../../shared/ui/toast/toast.service';

type GeoRow=GeographyProvince|GeographyCounty|GeographyCity;
interface GeoFilters{readonly provinceId:number|null;readonly countyId:number|null;readonly name:string;readonly status:'all'|'active'|'inactive';}
const EMPTY_FILTERS:GeoFilters={provinceId:null,countyId:null,name:'',status:'all'};

@Component({selector:'app-internal-geography',standalone:true,imports:[FormsModule,IconComponent,RouterLink],template:`
<div class="mx-auto max-w-[96%] space-y-4 animate-fade-in-up" dir="rtl">
 <header class="flex items-center gap-3"><span class="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10"><ui-icon name="map" [size]="25" class="text-primary"></ui-icon></span><div><h1 class="text-2xl font-black text-primary sm:text-3xl">مدیریت {{pluralLabel}}</h1><p class="text-sm text-muted">مدیریت سلسله‌مراتب مناطق جغرافیایی</p></div></header>
 <nav class="flex flex-wrap gap-2" aria-label="مدیریت مناطق جغرافیایی"><a class="tab" [class.active]="kind==='province'" routerLink="/fish24/internal/geography/provinces">استان‌ها</a><a class="tab" [class.active]="kind==='county'" routerLink="/fish24/internal/geography/counties">شهرستان‌ها</a><a class="tab" [class.active]="kind==='city'" routerLink="/fish24/internal/geography/cities">شهرها</a></nav>
 <section class="card p-4 sm:p-5"><div class="mb-3 flex items-center justify-between gap-3"><div class="flex items-center gap-2"><ui-icon name="search" [size]="18" class="text-primary"></ui-icon><h2 class="text-lg font-extrabold">جستجو</h2></div><button type="button" class="primary" (click)="openCreate()">جدید</button></div>
  <form class="grid items-end gap-3 sm:grid-cols-2 xl:grid-cols-5" (submit)="applyFilters($event)">
   @if(kind!=='province'){<label class="label">استان<select class="input" name="province" [(ngModel)]="draftFilters.provinceId" (change)="onFilterProvinceChange()"><option [ngValue]="null">همه استان‌ها</option>@for(p of service.provinces();track p.id){<option [ngValue]="p.id">{{p.name}}{{p.active?'':' (غیرفعال)'}}</option>}</select></label>}
   @if(kind==='city'){<label class="label">شهرستان<select class="input" name="county" [(ngModel)]="draftFilters.countyId"><option [ngValue]="null">همه شهرستان‌ها</option>@for(c of filterCounties();track c.id){<option [ngValue]="c.id">{{c.name}}{{c.active?'':' (غیرفعال)'}}</option>}</select></label>}
   <label class="label">نام {{singularLabel}}<input class="input" name="name" [(ngModel)]="draftFilters.name"></label>
   <label class="label">وضعیت<select class="input" name="status" [(ngModel)]="draftFilters.status"><option value="all">همه</option><option value="active">فعال</option><option value="inactive">غیرفعال</option></select></label>
   <div class="flex gap-2"><button class="primary" type="submit">جستجو</button><button class="secondary" type="button" (click)="showAll()">مشاهده همه</button></div>
  </form>
 </section>
 <section class="card overflow-hidden"><div class="flex flex-col gap-3 border-b border-border p-4 sm:flex-row sm:items-center sm:justify-between"><h2 class="text-lg font-extrabold">لیست {{pluralLabel}} ({{number(filteredRows().length)}} رکورد)</h2><div class="flex flex-wrap gap-2"><button type="button" class="toolbar" (click)="columnChooserOpen.set(!columnChooserOpen())">انتخاب ستون‌ها</button><button type="button" class="toolbar" (click)="exportRows()" [disabled]="!canExport()">خروجی Excel</button></div></div>
 @if(columnChooserOpen()){<div class="border-b border-border bg-background p-4"><div class="flex flex-wrap gap-3">@for(column of columns;track column.id){<label class="choice"><input type="checkbox" [checked]="visible(column.id)" [disabled]="onlyVisible(column.id)" (change)="toggleColumn(column.id,$event)">{{column.label}}</label>}</div><button class="secondary mt-3" type="button" (click)="restoreColumns()">بازگردانی ستون‌های پیش‌فرض</button></div>}
 <div class="overflow-x-auto"><table class="w-full min-w-max border-collapse text-right text-sm"><thead><tr class="bg-background">@for(column of visibleColumns();track column.id){<th class="border-b border-border px-3 py-3 align-top" [style.min-width]="column.minWidth"><button type="button" class="flex w-full items-center justify-between gap-2 font-extrabold" (click)="sort(column.id)"><span>{{column.label}}</span><span class="text-muted">{{sortMark(column.id)}}</span></button><input class="header-search mt-2" [value]="columnSearches()[column.id]||''" (input)="searchColumn(column.id,value($event))" [attr.aria-label]="'جستجو در '+column.label"></th>}<th class="border-b border-border px-3 py-3">عملیات</th></tr></thead><tbody>
 @for(row of pageRows();track row.id){<tr class="hover:bg-primary/5">@for(column of visibleColumns();track column.id){<td class="border-b border-border px-3 py-3 align-top">@if(column.id==='status'){<span [class]="row.active?'status-active':'status-inactive'">{{row.active?'فعال':'غیرفعال'}}</span>@if(row.active&&!service.effectivelyAvailable(kind,row.id)){<small class="mt-1 block text-warning">به‌دلیل غیرفعال‌بودن والد، برای انتخاب جدید در دسترس نیست</small>}}@else{<span>{{cellValue(column,row)}}</span>}</td>}<td class="border-b border-border px-3 py-3 align-top"><div class="flex flex-wrap gap-2"><button class="action" type="button" (click)="openEdit(row)">ویرایش</button><button class="action" type="button" (click)="toggle(row)">{{row.active?'غیرفعال‌کردن':'فعال‌کردن'}}</button></div></td></tr>}@empty{<tr><td [attr.colspan]="visibleColumns().length+1" class="p-8 text-center text-muted">رکوردی یافت نشد.</td></tr>}
 </tbody></table></div>@if(totalPages()>1){<div class="flex items-center justify-center gap-3 border-t border-border p-4"><button class="secondary" type="button" [disabled]="page()===1" (click)="page.set(page()-1)">قبلی</button><span>صفحه {{number(page())}} از {{number(totalPages())}}</span><button class="secondary" type="button" [disabled]="page()===totalPages()" (click)="page.set(page()+1)">بعدی</button></div>}
 </section>
 @if(editorOpen()){<div class="modal" role="dialog" aria-modal="true"><form class="dialog" (submit)="save($event)"><div class="flex items-center justify-between"><h2 class="text-xl font-black">{{editingId()===null?singularLabel+' جدید':'ویرایش '+singularLabel}}</h2><button class="icon-button" type="button" aria-label="بستن" (click)="closeEditor()">×</button></div><div class="mt-5 grid gap-4">
 @if(kind!=='province'){@if(editingId()===null){<label class="label">استان<select class="input" name="editProvince" [(ngModel)]="draft.provinceId" (change)="onEditorProvinceChange()"><option [ngValue]="null">انتخاب استان</option>@for(p of service.provinces();track p.id){@if(service.isProvinceAvailable(p.id)){<option [ngValue]="p.id">{{p.name}}</option>}}</select></label>}@else{<div><span class="label">استان</span><p class="readonly">{{editorProvinceName()}}</p></div>}}
 @if(kind==='city'){@if(editingId()===null){<label class="label">شهرستان<select class="input" name="editCounty" [(ngModel)]="draft.countyId"><option [ngValue]="null">انتخاب شهرستان</option>@for(c of editorCounties();track c.id){<option [ngValue]="c.id">{{c.name}}</option>}</select></label>}@else{<div><span class="label">شهرستان</span><p class="readonly">{{editorCountyName()}}</p></div>}}
 <label class="label">نام {{singularLabel}}<input class="input" name="editName" [(ngModel)]="draft.name"></label></div>@if(formError()){<p role="alert" class="mt-3 rounded-xl bg-danger/10 p-3 text-sm font-bold text-danger">{{formError()}}</p>}<div class="mt-5 flex justify-end gap-2"><button class="secondary" type="button" (click)="closeEditor()">انصراف</button><button class="primary" type="submit" [disabled]="submitting()">ذخیره</button></div></form></div>}
</div>`,styles:[`
.card{border:1px solid rgb(var(--color-border));border-radius:1rem;background:rgb(var(--color-surface));box-shadow:0 1px 3px rgb(15 23 42/.08)}.primary,.secondary,.toolbar,.action,.tab,.icon-button{display:inline-flex;min-height:2.55rem;align-items:center;justify-content:center;border-radius:.7rem;padding-inline:.9rem;font-size:.78rem;font-weight:800}.primary{background:rgb(var(--color-primary));color:#fff}.secondary,.toolbar,.action,.tab,.icon-button{border:1px solid rgb(var(--color-border));background:rgb(var(--color-surface))}.tab.active{border-color:rgb(var(--color-primary));background:rgb(var(--color-primary)/.1);color:rgb(var(--color-primary))}.label{display:flex;flex-direction:column;gap:.4rem;font-size:.75rem;font-weight:800}.input,.header-search,.readonly{width:100%;border:1px solid rgb(var(--color-border));border-radius:.65rem;background:rgb(var(--color-background));padding:.68rem .8rem;outline:none}.header-search{min-width:7rem;padding:.45rem .55rem;font-size:.72rem}.choice{display:flex;align-items:center;gap:.45rem;font-size:.78rem;font-weight:800}.status-active,.status-inactive{display:inline-flex;border-radius:999px;padding:.3rem .7rem;font-size:.7rem;font-weight:800}.status-active{background:rgb(var(--color-success)/.15);color:rgb(var(--color-success))}.status-inactive{background:rgb(var(--color-muted)/.15);color:rgb(var(--color-muted))}.modal{position:fixed;inset:0;z-index:90;display:flex;align-items:center;justify-content:center;background:rgb(2 6 23/.58);padding:.75rem}.dialog{width:100%;max-width:36rem;max-height:92vh;overflow:auto;border-radius:1rem;background:rgb(var(--color-surface));padding:1.25rem;box-shadow:0 20px 50px rgb(0 0 0/.25)}button:disabled{opacity:.45}@media(max-width:420px){.modal{align-items:flex-end}.dialog{border-bottom-left-radius:0;border-bottom-right-radius:0}}
` ]})
export class InternalGeographyComponent{
 readonly service=inject(Fish24GeographyService);private readonly route=inject(ActivatedRoute);private readonly roles=inject(Fish24RolePreviewService);private readonly prefs=inject(InternalListPreferencesService);private readonly xlsx=inject(PlainXlsxService);private readonly toast=inject(ToastService);
 readonly kind=this.route.snapshot.data['kind'] as GeographyKind;readonly singularLabel=this.kind==='province'?'استان':this.kind==='county'?'شهرستان':'شهر';readonly pluralLabel=this.kind==='province'?'استان‌ها':this.kind==='county'?'شهرستان‌ها':'شهرها';readonly listId=`internal-geography-${this.kind}`;
 readonly page=signal(1);readonly pageSize=10;readonly columnChooserOpen=signal(false);readonly editorOpen=signal(false);readonly editingId=signal<number|null>(null);readonly formError=signal('');readonly submitting=signal(false);draft={provinceId:null as number|null,countyId:null as number|null,name:''};
 readonly appliedFilters=signal(this.loadFilters());draftFilters={...this.appliedFilters()};readonly columnSearches=signal<InternalListColumnSearches>({});readonly tableSort=signal<InternalListSort>({columnId:null,direction:null});
 readonly columns:readonly InternalListColumn<GeoRow>[]=[{id:'id',label:'شناسه',value:r=>String(r.id),exportValue:r=>String(r.id),minWidth:'6rem'}, {id:'name',label:'نام',value:r=>r.name,minWidth:'14rem'},...(this.kind==='city'?[{id:'county',label:'نام شهرستان',value:(r:GeoRow)=>this.countyNameFor(r),minWidth:'12rem'}]:[]),...(this.kind!=='province'?[{id:'province',label:'نام استان',value:(r:GeoRow)=>this.provinceNameFor(r),minWidth:'12rem'}]:[]),{id:'createdAt',label:'تاریخ ایجاد',value:r=>r.createdAt,minWidth:'10rem'},{id:'status',label:'وضعیت',value:r=>r.active?'فعال':'غیرفعال',minWidth:'8rem'}];
 readonly allColumnIds=this.columns.map(x=>x.id);readonly defaultColumnIds=[...this.allColumnIds];readonly selectedColumns=signal<readonly string[]>(this.prefs.load(this.listId,this.allColumnIds,this.defaultColumnIds));readonly visibleColumns=computed(()=>this.columns.filter(x=>this.selectedColumns().includes(x.id)));
 readonly sourceRows=computed<readonly GeoRow[]>(()=>this.kind==='province'?this.service.provinces():this.kind==='county'?this.service.counties():this.service.cities());readonly filteredRows=computed(()=>{const f=this.appliedFilters();return this.sourceRows().filter(r=>(!f.name||r.name.includes(f.name))&&(f.status==='all'||r.active===(f.status==='active'))&&(this.kind==='province'||!f.provinceId||this.provinceIdFor(r)===f.provinceId)&&(this.kind!=='city'||!f.countyId||this.countyIdFor(r)===f.countyId));});readonly tableRows=computed(()=>sortInternalListRows(filterByInternalListColumns(this.filteredRows(),this.columns,this.selectedColumns(),this.columnSearches()),this.columns,this.tableSort()));readonly pageRows=computed(()=>this.tableRows().slice((this.page()-1)*this.pageSize,this.page()*this.pageSize));readonly totalPages=computed(()=>Math.max(1,Math.ceil(this.tableRows().length/this.pageSize)));
 filterCounties(){return this.service.counties().filter(c=>!this.draftFilters.provinceId||c.provinceId===this.draftFilters.provinceId);}editorCounties(){return this.service.counties().filter(c=>c.provinceId===this.draft.provinceId&&this.service.isCountyAvailable(c.id));}
 canExport(){return this.service.canExport(this.roles.getPreviewRole());}number(v:number){return new Intl.NumberFormat('fa-IR').format(v);}value(e:Event){return(e.target as HTMLInputElement).value;}visible(id:string){return this.selectedColumns().includes(id);}onlyVisible(id:string){return this.visible(id)&&this.selectedColumns().length===1;}cellValue(c:InternalListColumn<GeoRow>,r:GeoRow){return c.value(r);}
 provinceIdFor(r:GeoRow){return this.kind==='county'?(r as GeographyCounty).provinceId:this.kind==='city'?this.service.provinceForCity(r.id)?.id??null:r.id;}countyIdFor(r:GeoRow){return this.kind==='city'?(r as GeographyCity).countyId:null;}provinceNameFor(r:GeoRow){return this.kind==='county'?this.service.provinceName((r as GeographyCounty).provinceId):this.kind==='city'?this.service.provinceForCity(r.id)?.name??'—':r.name;}countyNameFor(r:GeoRow){return this.kind==='city'?this.service.countyName((r as GeographyCity).countyId):'—';}
 applyFilters(e:Event){e.preventDefault();const f={...this.draftFilters,name:this.draftFilters.name.trim()};this.appliedFilters.set(f);this.prefs.saveFilters(this.listId,f);this.page.set(1);}showAll(){this.draftFilters={...EMPTY_FILTERS};this.appliedFilters.set(EMPTY_FILTERS);this.prefs.resetFilters(this.listId);this.page.set(1);}onFilterProvinceChange(){if(this.draftFilters.countyId&&!this.filterCounties().some(c=>c.id===this.draftFilters.countyId))this.draftFilters.countyId=null;}
 toggleColumn(id:string,e:Event){const checked=(e.target as HTMLInputElement).checked;const next=checked?[...this.selectedColumns(),id]:this.selectedColumns().filter(x=>x!==id);if(!next.length)return;this.selectedColumns.set(this.prefs.save(this.listId,next,this.allColumnIds));if(!checked)this.searchColumn(id,'');}restoreColumns(){this.selectedColumns.set(this.prefs.reset(this.listId,this.allColumnIds,this.defaultColumnIds));this.columnSearches.set({});this.tableSort.set({columnId:null,direction:null});}searchColumn(id:string,q:string){this.columnSearches.update(v=>({...v,[id]:q}));this.page.set(1);}sort(id:string){this.tableSort.update(v=>nextInternalListSort(v,id));}sortMark(id:string){const s=this.tableSort();return s.columnId===id?(s.direction==='asc'?'↑':'↓'):'↕';}
 openCreate(){this.editingId.set(null);this.draft={provinceId:null,countyId:null,name:''};this.formError.set('');this.editorOpen.set(true);}openEdit(row:GeoRow){this.editingId.set(row.id);this.draft={provinceId:this.provinceIdFor(row),countyId:this.countyIdFor(row),name:row.name};this.formError.set('');this.editorOpen.set(true);}closeEditor(){if(!this.submitting())this.editorOpen.set(false);}onEditorProvinceChange(){this.draft.countyId=null;}editorProvinceName(){return this.draft.provinceId?this.service.provinceName(this.draft.provinceId):'—';}editorCountyName(){return this.draft.countyId?this.service.countyName(this.draft.countyId):'—';}
 save(e:Event){e.preventDefault();if(this.submitting())return;this.submitting.set(true);const role=this.roles.getPreviewRole(),id=this.editingId();let result;if(this.kind==='province')result=id===null?this.service.createProvince(role,this.draft.name):this.service.updateProvince(role,id,this.draft.name);else if(this.kind==='county')result=id===null?this.service.createCounty(role,this.draft.provinceId??0,this.draft.name):this.service.updateCounty(role,id,this.draft.provinceId??0,this.draft.name);else result=id===null?this.service.createCity(role,this.draft.provinceId??0,this.draft.countyId??0,this.draft.name):this.service.updateCity(role,id,this.draft.countyId??0,this.draft.name);this.submitting.set(false);if(!result.ok){this.formError.set(result.error);return;}this.editorOpen.set(false);this.toast.show(id===null?'رکورد جدید ثبت شد.':'تغییرات ذخیره شد.','success');}
 toggle(row:GeoRow){const result=this.service.toggle(this.roles.getPreviewRole(),this.kind,row.id);this.toast.show(result.ok?(row.active?'رکورد غیرفعال شد.':'رکورد فعال شد.'):result.error,result.ok?'success':'error');}
 exportRows(){if(!this.canExport()){this.toast.show('مجوز خروجی مناطق جغرافیایی را ندارید.','error');return;}const columns=this.visibleColumns();const rows=this.filteredRows().map(r=>columns.map(c=>c.exportValue?c.exportValue(r):c.value(r)==null?null:c.value(r) as string|number));this.xlsx.export(`fish24-${this.kind}s.xlsx`,columns.map(c=>c.label),rows);this.toast.show('خروجی Excel آماده شد.','success');}
 private loadFilters(){return this.prefs.loadFilters<GeoFilters>(this.listId,EMPTY_FILTERS,value=>{if(typeof value!=='object'||value===null)return null;const f=value as Partial<GeoFilters>,provinceId=f.provinceId??null,countyId=f.countyId??null;if((provinceId!==null&&typeof provinceId!=='number')||(countyId!==null&&typeof countyId!=='number')||typeof f.name!=='string'||!['all','active','inactive'].includes(f.status??''))return null;if(provinceId!==null&&!this.service.province(provinceId))return null;const county=countyId===null?null:this.service.county(countyId);if(countyId!==null&&!county)return null;if(county&&provinceId!==null&&county.provinceId!==provinceId)return null;return{provinceId:this.kind==='province'?null:provinceId,countyId:this.kind==='city'?countyId:null,name:f.name,status:f.status as GeoFilters['status']};});}
}
